auth0/auth0.net

Auth0.Net-tests/ConnectionsTests.cs
Auth0.Net/Client.cs
README.md

Added GenerateVerificationTicket method to the client to allow generation of the email verification url. This is useful when people send out custom emails in which they want to include an email verification link.

Support email verification ticket

---

Auth0.Net/Auth0.Net.csproj
Auth0.Net/Client.cs
Auth0.Net/UserValidationResult.cs
README.md

This endpoint is required if you're building a secure password reset form which doesn't use email verification. You could present the user with 4 input fields:
- Username
- Current password
- New password
- Confirm new password
The username and current password would then be validated, and if both are correct the user's password can be changed to the new password.

Support username/password validation

---

Auth0.Net/Client.cs

I have been having issues with GetErrorDetails throwing a NullReferenceException when no details exist in a response (using an older client version). 
Although a fix was implemented about a month ago this pull request improves on that change by avoiding exceptions altogether plus a few other enhancements such as avoiding a JSON round-trip and providing a simple default message in the case of no further details.

Consistent, simplified and improved error messages

---

Auth0.Net/Auth0.Net.csproj
Auth0.Net/packages.config

Issue 40: Client.ExchangeAuthorizationCodePerAccessToken throws OAuthException in .NET 3.5

---

Auth0.Net/Client.cs

Under certain circumstances, the RestSharp response has no body and is
causing a `NullReferenceException`.  This change prevents that as well as reports back more meaningful errors for other scenarios.

Improve error handling in ExchangeAuthorizationCodePerAccessToken

---

examples/webapi/Api/App_Start/WebApiConfig.cs
examples/webapi/Api/Web.config

For the ASP.NET WebAPI seed, updates the names of the keys set in
web.config and used in WebApiConfig.cs, so that they are the same used
by the Auth0-ASPNET nuget package.

Fix issue 354

---

examples/webapi/README.md

This is part of issue #68 in [Auth0 docs repo](https://github.com/auth0/docs).

Issue #68: Add reference to .NET CORS package.

---

src/Auth0.AuthenticationApi/Models/AuthenticationResponse.cs

Could not convert JSON to object (properties were all null). This solved it for me as the returned json was different from the object format.
Let me know if this commit is correct, so I can use the nuget version.

Fix Authentication Response NULL

---

src/Auth0.AuthenticationApi/Auth0.AuthenticationApi.csproj
src/Auth0.AuthenticationApi/AuthenticationApiClient.cs
src/Auth0.AuthenticationApi/IAuthenticationApiClient.cs
src/Auth0.AuthenticationApi/Models/UsernamePasswordLoginRequest.cs
src/Auth0.AuthenticationApi/Models/UsernamePasswordLoginResponse.cs
src/Auth0.Core/ApiErrorContractResolver.cs
src/Auth0.Core/Auth0.Core.csproj
src/Auth0.ManagementApi/Core/Http/ApiConnection.cs

This adds support for the usernamepassword/login endpoint. This endpoint will return a WS-Fed form instead of a JWT. Advantages:
- This will be posted to Auth0 to the end user, which means SSO can be leveraged (Auth0 will set an SSO cookie)
- You can use a code flow with this, allowing you to build custom login pages in combination with the Auth0 OWIN middleware for MVC.
Usage:
var response = await auth.UsernamePasswordLogin(new Auth0.AuthenticationApi.Models.UsernamePasswordLoginRequest()
{
ClientId = "111",
Username = "user@something.com",
Password = "mypass",
Connection = "Username-Password-Authentication",
RedirectUri = "http://localhost:3001/login",
Scope = "openid name"
});
Response:
```
<form method="post" name="hiddenform" action="https://me.auth0.com/login/callback">
<input …
```

Add implmenetation for username password login endpoint

---

src/Auth0.AuthenticationApi/Models/AccessToken.cs
src/Auth0.AuthenticationApi/Models/AuthenticationResponse.cs

Please also allow the following properties to be implemented for the use of refreshtokens:
AuthenticationResponse:
- refresh_token
AccessToken
- expires_in

Missing properties for refreshtokens

---

src/Auth0.AuthenticationApi/Models/PasswordlessEmailRequest.cs
tests/Auth0.AuthenticationApi.IntegrationTests/PasswordlessTests.cs

The authentication API expects a JSON object, not a string.
This is a breaking change because of the type change, but probably nobody is using the parameter right now as it is, because it's not working. 
Would it be ok to issue it as a minor version only?

Corrects the type for AuthenticationParams in passwordless/start

---

src/Auth0.Core/Identity.cs
tests/Auth0.ManagementApi.IntegrationTests/UsersTests.cs

Adds support for reading the 'profileData' property of a secondary identity thas has been linked to a primary identity. 
E.g. raw user JSON:
```
{
"email": "027d4dee653d4dfbba9deb64d6ad6bbb@nonexistingdomain.aaa",
"email_verified": true,
"user_id": "auth0|58658a88ef793e559a05bafb",
"picture": "https://s.gravatar.com/avatar/7476381b06763751bed7fef7fac1ae90?s=480&r=pg&d=https%3A%2F%2Fcdn.auth0.com%2Favatars%2F02.png",
"identities": [
{
"connection": "ec1e7da1629c4ad49fa7910a5181feee",
"user_id": "58658a88ef793e559a05bafb",
"provider": "auth0",
"isSocial": false
},
{
"profileData": {
"email": "f1b31ca358f24e5b8b0a6f9b06aef650@nonexistingdomain.aaa",
"email_verified": true
},
"connection": "ec1e7da1629c4ad49fa7910a5181feee",
"user_id": "58658a89ef793e559a05bafc",
"provider": "auth0", …
```

Support for profileData on linked identities

---

src/Auth0.ManagementApi/Models/Identity.cs

This will allow refresh tokens to be obtained when retrieving users from the Management API if the appropriate scopes are specified in the access token.

 Add refresh token property in user identity

---

src/Auth0.AuthenticationApi/AuthenticationApiClient.cs

I have a rule that need that info for scope attribution.
And the fact that the attribute exist in the model and is not used is kind of confusing.

Add RefreshTokenRequest Audience to actual request

---

src/Auth0.AuthenticationApi/AuthenticationApiClient.cs
src/Auth0.Core/Http/ApiConnection.cs
src/Auth0.ManagementApi/ManagementApiClient.cs

In reference to #165 I've spiked out opening up the AuthenticationApiClient to allow consumers to inject their own HttpClient that they can manage the lifetime of per their application requirements.
This is to help comply with what is given on MSDN regarding HttpClient socket exhaustion: https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclient?view=netframework-4.7 `HttpClient is intended to be instantiated once and re-used throughout the life of an application. Instantiating an HttpClient class for every request will exhaust the number of sockets available under heavy loads. This will result in SocketException errors.`
Let me know if you'd like for me to extend this into the ManagementApiClient before acceptance or if you'd like specific test cases written.

Inject HttpClient into AuthenticationApiClient 

---

src/Auth0.AuthenticationApi/AuthenticationApiClient.cs
src/Auth0.AuthenticationApi/Models/ResourceOwnerTokenRequest.cs

The current option to add a auth0-forwarded-for header to ROPC token requests, is to implement a custom Http​Message​Handler and overriding SendAsync. However, this removes the possibility to provide a reusable HttpClient. Since this header is an official feature of ROPC token requests, I think it is ok to add the option of using it to the ResourceOwnerTokenRequest.
I looked for any tests that should be adapted for this change, but could not find any. Please point me in the right direction if any more work needs to be done.

Possibility to add an auth0-forwarded-for header to ROPC token requests

---

src/Auth0.Core/Http/ApiInfo.cs
src/Auth0.Core/Http/ApiInfoParser.cs

This adds ServerTime to ApiInfo as discussed in #200.
Had to use a nullable DateTimeoffset because the header could technically have been left out by the server.

Add ServerTime to ApiInfo

---

.idea/.idea.Auth0.Net/.idea/contentModel.xml
src/Auth0.AuthenticationApi/Auth0.AuthenticationApi.csproj
src/Auth0.AuthenticationApi/AuthenticationApiClient.cs
src/Auth0.AuthenticationApi/Exceptions/IdentityTokenValidationException.cs
src/Auth0.AuthenticationApi/IdentityTokenValidator.cs
src/Auth0.AuthenticationApi/Models/ResourceOwnerTokenRequest.cs
src/Auth0.AuthenticationApi/OpenIdConfigurationCache.cs
src/Auth0.Core/Auth0.Core.csproj
src/Auth0.Core/Http/Utils.cs
src/Auth0.ManagementApi/Auth0.ManagementApi.csproj
tests/Auth0.AuthenticationApi.IntegrationTests/Auth0.AuthenticationApi.IntegrationTests.csproj
tests/Auth0.AuthenticationApi.IntegrationTests/IdentityTokenValidatorTests.cs
tests/Auth0.AuthenticationApi.IntegrationTests/OpenIdConfigurationCacheTests.cs

Added ID token validation to methods calling the `/oauth/token` endpoint.
The ID Token validation use the built-in JWT token validation methods which does a full validation for RS256 tokens - it checks `nbf` and `exp` claims, validates the issuer, validates the audience and validates the signature.
This also downloads (and caches) the JWKS from the `.well-known/openid-configuration` endpoint and will use those keys for the signature validation.
Test coverage ensures that token validation passes under correct circumstances for both normal tenant URL, as well as for CNAME.
Tests also ensures that validation fails when incorrect issuer and audience is passed.

ID Token validation

---

src/Auth0.ManagementApi/Clients/CustomDomainsClient.cs
src/Auth0.ManagementApi/Clients/ICustomDomainsClient.cs
src/Auth0.ManagementApi/IManagementApiClient.cs
src/Auth0.ManagementApi/ManagementApiClient.cs
src/Auth0.ManagementApi/Models/CustomDomain.cs
src/Auth0.ManagementApi/Models/CustomDomainBase.cs
src/Auth0.ManagementApi/Models/CustomDomainCertificateProvisioning.cs
src/Auth0.ManagementApi/Models/CustomDomainCreateRequest.cs
src/Auth0.ManagementApi/Models/CustomDomainStatus.cs
src/Auth0.ManagementApi/Models/CustomDomainVerification.cs
src/Auth0.ManagementApi/Models/CustomDomainVerificationResponse.cs
tests/Auth0.ManagementApi.IntegrationTests/CustomDomainsTests.cs

This adds support for the `/api/v2/custom-domains` endpoints to allow users to manage custom domains using the Auth0 .NET SDK.
Writing automated tests for this is challenging as the `auth0-dotnet-integration-tests.auth0.com` tenant does not support custom domains. I wrote some tests agains the `brucke.auth0.com` tenant, but this is also limited since that tenant allows for only one custom domain, and I cannot delete it since team Brucke actually depends on that custom domain for their tests.
I believe I have done enough though to exercise the various endpoints to ensure that endpoints are called correctly and that payload serialization and deserialization happens correctly.

Add custom domain support

---

src/Auth0.ManagementApi/Models/ResourceServerBase.cs
tests/Auth0.ManagementApi.IntegrationTests/ResourceServerTests.cs

Adds a missing property from /resource-servers API endpoint

Add token_lifetime_for_web to ResourceServerBase

---

src/Auth0.ManagementApi/Models/ResourceServerBase.cs
tests/Auth0.ManagementApi.IntegrationTests/ResourceServerTests.cs

PR #208 added the TokenLifetimeForWeb property to the API however being an integer it defaults to zero which is invalid and would break existing clients until they set it to a valid value.
This PR makes it nullable so that if if a value is not set then it will not send a value and keep the existing behavior.

Nullable TokenLifetimeForWeb for backward compat

---

tests/Auth0.ManagementApi.IntegrationTests/TestBase.cs

Prevent tests from trying to write with missing configuration values/environment variables.

Check configuration values are set in tests

---

build.cake

The cake build script previously only ran the pack if it was on AppVeyor or the "pack" command was specifically called.  We want the default to run both on CI in a single build.

Modify cake to allow build+test+pack in a single step

---

src/Auth0.AuthenticationApi/AuthenticationApiClient.cs
src/Auth0.Core/Auth0.Core.csproj
src/Auth0.Core/Http/ApiConnection.cs
src/Auth0.Core/Http/DiagnosticsComponent.cs
src/Auth0.Core/Http/DiagnosticsHeader.cs
src/Auth0.Core/Http/Utils.cs
src/Auth0.ManagementApi/ManagementApiClient.cs
tests/Auth0.Core.UnitTests/Auth0ClientTests.cs

- Changes SDK name to 'Auth0.net'
- Deprecate dependencies and environment telemetry
- Add limited 'target' via 'env' which tracks build of the SDK
- Deprecates DiagnosticsHeader entirely as it now has little use and doubles number of constructors on entry classes
Example:
```json
{"name":"Auth0.Net","version":"5.11.0","env":{"target":"NETSTANDARD2.0"}}
```
Adding CLR runtime is unfortunately non-trivial.  Operating System could be added but is of limited value.

Simplify telemetry and deprecate DiagnosticsHeader

---

src/Auth0.Core/Http/ApiConnection.cs
src/Auth0.ManagementApi/ManagementApiClient.cs
tests/Auth0.ManagementApi.IntegrationTests/ApiConnectionTests.cs
tests/Auth0.ManagementApi.IntegrationTests/ManagementApiClientTests.cs

If ApiConnection creates a HttpClient it should dispose of it as well (ApiConnection owns it)
HttpClients that are created outside of ApiConnection and passed in via the constructor should not be disposed (ApiConnection does not own it)
Fixes #192

ApiConnection should dispose HttpClient if it creates it

---

src/Auth0.ManagementApi/Clients/ClientBase.cs
src/Auth0.ManagementApi/Clients/RolesClient.cs
src/Auth0.ManagementApi/Models/AssignRolesRequest.cs
src/Auth0.ManagementApi/Models/AssignUsersRequest.cs
src/Auth0.ManagementApi/Models/AssociatePermissionsRequest.cs
src/Auth0.ManagementApi/Models/Permission.cs
src/Auth0.ManagementApi/Models/PermissionIdentity.cs
src/Auth0.ManagementApi/Models/ResourceServerBase.cs
tests/Auth0.ManagementApi.IntegrationTests/RolesTests.cs

Adds the permission endpoints as requested in #246 
Also fixes a couple of XML doc comments and makes ResourceServer.TokenLifetime nullable so you can patch it without changing it.

Add role permission endpoints to RoleClient

---

tests/Auth0.ManagementApi.IntegrationTests/RolesTests.cs

During some clean-up of auto-generated resources on the integration test tenant one of the resources actually used by a test was removed.  Switched over to a different one that does not look so auto-generated/left over from a broken test run.

Fix integration test caused by deletion of resource server

---

src/Auth0.ManagementApi/Clients/RolesClient.cs
src/Auth0.ManagementApi/Clients/UsersClient.cs
src/Auth0.ManagementApi/Models/AssociatePermissionsRequest.cs
tests/Auth0.ManagementApi.IntegrationTests/RolesTests.cs
tests/Auth0.ManagementApi.IntegrationTests/UsersTests.cs

1. Adds `GET users/{id}/permissions` endpoint as `Users.GetPermissionsAsync(...)`
2. Adds `POST users/{id}/permissions` endpoint as `Users.AssignPermissionsAsync(...)`
3. Adds `DELETE users/{id}/permissions` endpoint as `Users.RemovePermissionsAsync(...)`
Also adjusts the existing naming on RolesClient permissions endpoints to be consistent with the API documentation.  Associate and Unassociate is now Assign and Remove.

Add missing user permissions endpoints

---

src/Auth0.AuthenticationApi/AuthenticationApiClient.cs
src/Auth0.Core/Http/ApiConnection.cs
src/Auth0.ManagementApi/ManagementApiClient.cs
tests/Auth0.AuthenticationApi.IntegrationTests/AuthenticationApiClientTests.cs

1. Add's IDisposable support to AuthenticationApiClient to match ManagementApiClient
2. Consolidates ManagementApiClient constructors in a source-compatible way
3. Adds missing Dispose xmldoc comments
cc @nicosabena

Add IDisposable support to AuthenticationApiClient

---

src/Auth0.ManagementApi/Models/ResourceServerBase.cs
src/Auth0.ManagementApi/Models/TokenDialect.cs
tests/Auth0.ManagementApi.IntegrationTests/ResourceServerTests.cs

Added missing properties to the ResourceServer (Base) class:
1. VerificationLocation
2. TokenDialect 
3. EnforcePolicies 
Also made some properties that were supposed to be optional actually optional:
1. SigningAlgorithm
2. AllowOfflineAccess
3. SkipConsentForVerifiableFirstPartyClients

Add missing properties to ResourceServer

---

src/Auth0.ManagementApi/Clients/UsersClient.cs
src/Auth0.ManagementApi/Models/EnrollmentAuthMethod.cs
src/Auth0.ManagementApi/Models/EnrollmentStatus.cs
src/Auth0.ManagementApi/Models/EnrollmentsResponse.cs
src/Auth0.ManagementApi/Models/GenerateRecoveryCodeResponse.cs
tests/Auth0.ManagementApi.IntegrationTests/UsersTests.cs

Three Guardian-related endpoints were missed in #240 as they live on the User endpoints not Guardian.
Also noticed "users-by-email" did not have an integration test.
Fixes #270

Add missing User endpoints for Guardian

---

src/Auth0.ManagementApi/Models/TenantSettingsBase.cs

This corrects the type of SessionLifetime and IdleSessionLifetime on the TenantSettings(Base) class.
Fixes #271

Correct numeric type for lifetimes on TenantSettings

---

src/Auth0.ManagementApi/Models/User.cs

The following fields are optional but were not nullable:
- CreatedAt
- LastLogin
- UpdatedAt
Fixes #276

Make user model optional fields nullable

---

build/common.props
src/Auth0.AuthenticationApi/Auth0.AuthenticationApi.csproj
src/Auth0.Core/Auth0.Core.csproj
src/Auth0.ManagementApi/Auth0.ManagementApi.csproj

This PR changes the explicit declaration of `DocumentationFile` into `GenerateDocumentationFile` where the name of the xml file will be determined automatically.

Use GenerateDocumentationFile instead to specify if the xml documentation should be created.

---

src/Auth0.ManagementApi/Clients/RolesClient.cs

- Pass pagination parameters as `queryStrings` instead of `urlSegments`
- Previously, the pagination parameters were ignored, now they are respected
Fixes #282

Fix pagination in roles client

---

src/Auth0.ManagementApi/Clients/UsersClient.cs

Fixed the `UsersClient.GetPermissionsAsync` method's parameters. Split the `urlSegments` param and `queryStrings` param into two dictionaries while making the request. This change is now in line with other clients' GET methods that return paging information along with the response.
Issue 284: https://github.com/auth0/auth0.net/issues/284
A call to `UsersClient.GetPermissionsAsync`  should return the paging information now in the `Paging` object on `IPagedList<Permission>`.

Issue#284: Fixing pagination in UsersClient GetPermissionsAsync

---

src/Auth0.ManagementApi/Clients/RolesClient.cs
src/Auth0.ManagementApi/Clients/UsersClient.cs
tests/Auth0.ManagementApi.IntegrationTests/RolesTests.cs
tests/Auth0.ManagementApi.IntegrationTests/UsersTests.cs

Permission paging was broken as it was looking for the wrong property in the returned object.
Added integration tests.

Fix permission paging bug

---

build/common.props

Fixes get permission calls returning no results on users and roles when paging specified.

Prepare 6.5.1 release

---

tests/Auth0.AuthenticationApi.IntegrationTests/UriBuildersTests.cs

URL encoding subtly changed in .NET Core 2.0.
Some tests were expecting `:` to be unencoded. Now they are encoded.

Fix failing tests 

---

src/Auth0.ManagementApi/Models/VerifyEmailJobRequest.cs
tests/Auth0.ManagementApi.IntegrationTests/JobsTest.cs

@damieng, as discussed I've added ClientId parameter for the verify email job request to bring it in line with the API spec, changed the VerifyEmailJobRequest class
https://github.com/auth0/auth0.net/issues/292
https://auth0.com/docs/api/management/v2#!/Jobs/post_verification_email
I experience the `Global limit has been reached`, I ran each test individually so should be fine, anything should be caught in CI/CD test coverage

Add ClientId to the VerifyEmailJobRequest as per the API specification

---

src/Auth0.ManagementApi/Models/ClientBase.cs
tests/Auth0.ManagementApi.IntegrationTests/ClientTests.cs

There exists no current way to set the initiate_login_uri property on a client through this library support for the management API
- Added property InitiateLoginUri to Auth0.ManagementApi.Models.ClientBase class so this property can be set and retrieved
- Updated client CRUD integration test
We require this change to support our development as we make use of this library in our application. We need a way to be able to get & set this property for CRUD operations on Client
- Existing tests have been run and complete without errors
- Updated client CRUD integration test
Please describe how this can be tested by reviewers. Be specific about anything not tested and reasons why. If this library has unit and/or integration testing, tests should be added for new functionality and existing tests …

ClientBase now has initiate_login_uri property

---

src/Auth0.AuthenticationApi/Builders/AuthorizationUrlBuilder.cs
tests/Auth0.AuthenticationApi.IntegrationTests/UriBuildersTests.cs

Adding **WithConnectionScope** to **AuthorizationUrlBuilder **
Actually, the AuthorizationUrlBuilder does not offer any way to include Connection Scopes when building the authorization URL. This forces us to concatenate the aforementioned field manually, e.g.:
```
using (var authenticationApiClient = new AuthenticationApiClient(new Uri("BASE_URL")))
{
var urlBuilder = authenticationApiClient.BuildAuthorizationUrl();
urlBuilder
// More stuff...
.WithScope("offline_access openid");
var url = urlBuilder.Build();
return url.AbsoluteUri + "&connection_scope=IDP scopes";
}
```
By introducing this new method *WithConnectionScope*, we will be able to include connection scopes following the same fluent-api approach the builder already uses, resulting in a cleaner solution. E.g.:
```
using (var …
```

WithConnectionScope method added to AuthorizationUrlBuilder

---

src/Auth0.AuthenticationApi/Builders/AuthorizationUrlBuilder.cs
src/Auth0.AuthenticationApi/Builders/LogoutUrlBuilder.cs
src/Auth0.AuthenticationApi/Builders/SamlUrlBuilder.cs
src/Auth0.AuthenticationApi/Builders/UrlBuilderBase.cs
src/Auth0.AuthenticationApi/Builders/WsFedUrlBuilder.cs
src/Auth0.AuthenticationApi/Models/AuthorizationResponseType.cs
tests/Auth0.AuthenticationApi.IntegrationTests/UriBuildersTests.cs

Improves the URL builders by:
1. Improving the doc comments everywhere including adding links to online Auth API ref
2. Adding `Url` class alternatives to the `string` ones that take URLs (constructors and methods)
3. Switches from `AddQueryValue` + `return` to just `WithValue` for shorter code
4. Adds methods that take arrays of parameters for things like Scopes so users don't need to know separator rules
5. Removes the `WithAccessToken` method from AuthorizationBuilder... no idea what this was supposed to be for but it's not part of what's accepted.

Improve API builders

---

src/Auth0.AuthenticationApi/AuthenticationApiClient.cs
src/Auth0.AuthenticationApi/AuthenticationApiClientExtensions.cs
src/Auth0.AuthenticationApi/IAuthenticationApiClient.cs

Right now the `IAuthenticationApiClient` interface exposes all the builders in order to be helpful and the `AuthenticationApiClient` implements them.
As these are just builders that require a URL and not any actual requirement on a connection unlike the rest of the client it really is a muddling of concerns.
I have instead split these methods out to an extension class so people using them will continue to do so without either the interface or class having to deal with multiple concerns.

Split builders from auth client

---

src/Auth0.AuthenticationApi/AuthenticationApiClient.cs
src/Auth0.AuthenticationApi/JwtSignatureAlgorithm.cs
src/Auth0.AuthenticationApi/Models/AuthorizationCodeRequestBase.cs
src/Auth0.AuthenticationApi/Models/AuthorizationCodeTokenRequest.cs
src/Auth0.AuthenticationApi/Models/ClientCredentialsTokenRequest.cs
src/Auth0.AuthenticationApi/Models/RefreshTokenRequest.cs
src/Auth0.AuthenticationApi/Models/ResourceOwnerTokenRequest.cs
src/Auth0.AuthenticationApi/Tokens/IdTokenValidator.cs
tests/Auth0.AuthenticationApi.IntegrationTests/Tokens/IdTokenValidatorIntegrationTests.cs
tests/Auth0.AuthenticationApi.IntegrationTests/Tokens/IdTokenValidatorTests.cs

This wires up the previously checked in HS256 symmetric signature verifier from #326 completing the OIDC compliance work for this SDK with the exception of Jwks caching and invalidation to follow.
Developers can chose between HS256 and RS256 depending on what their client/application is configured for. This is done on a per-request basis just like ClientId and ClientSecret.  Ideally I think the auth client should take all three pieces of information once but there have been enough breaking changes in this major.
I have made RS256 the default.  If developers are using HS256 they will need to set their requests to RS256 or they will get token validation errors.  This will be included in the migration guide.

Improved OIDC compliance (part 3, wire up HS256) 

---

src/Auth0.ManagementApi/Clients/BaseClient.cs
src/Auth0.ManagementApi/Clients/BlacklistedTokensClient.cs
src/Auth0.ManagementApi/Clients/ClientGrantsClient.cs
src/Auth0.ManagementApi/Clients/ClientsClient.cs
src/Auth0.ManagementApi/Clients/ConnectionsClient.cs
src/Auth0.ManagementApi/Clients/CustomDomainsClient.cs
src/Auth0.ManagementApi/Clients/DeviceCredentialsClient.cs
src/Auth0.ManagementApi/Clients/EmailProviderClient.cs
src/Auth0.ManagementApi/Clients/EmailTemplatesClient.cs
src/Auth0.ManagementApi/Clients/GuardianClient.cs
src/Auth0.ManagementApi/Clients/JobsClient.cs
src/Auth0.ManagementApi/Clients/LogsClient.cs
src/Auth0.ManagementApi/Clients/ResourceServersClient.cs
src/Auth0.ManagementApi/Clients/RolesClient.cs
src/Auth0.ManagementApi/Clients/RulesClient.cs
src/Auth0.ManagementApi/Clients/StatsClient.cs
src/Auth0.ManagementApi/Clients/TenantSettingsClient.cs
src/Auth0.ManagementApi/Clients/TicketsClient.cs
src/Auth0.ManagementApi/Clients/UserBlocksClient.cs
src/Auth0.ManagementApi/Clients/UsersClient.cs
src/Auth0.ManagementApi/HttpClientManagementConnection.cs
src/Auth0.ManagementApi/IManagementConnection.cs
src/Auth0.ManagementApi/ManagementApiClient.cs
tests/Auth0.ManagementApi.IntegrationTests/HttpClientManagementConnectionTests.cs
tests/Auth0.ManagementApi.IntegrationTests/ManagementApiClientTests.cs

Part of the new connection design was the intent to allow management connections to be shared between clients giving another vector for sharing HttpClients that is easier than manually creating them and passing to each connection.
Unfortunately, the design included a default headers mechanism that prevented the management connection from being used for more than one tenant at a time.  While we could have documented this it's easier to just not have this edge case ever happen and as a benefit, it simplifies the code and the interface.
This moves the responsibility for managing the headers out from the connection and up into the client with the baseclient taking care to capture them.
Most of this PR is just adding "DefaultHeaders" to various calls (all the *Client classes). In fact there's …

Allow management connections to be shared between hosts

---

src/Auth0.AuthenticationApi/Tokens/IdTokenClaimValidator.cs
tests/Auth0.AuthenticationApi.IntegrationTests/Tokens/IdTokenClaimValidatorTests.cs

Removes the check that the IAT claim must be in the future. 
While the IAT must be present in an ID token and we continue to check the value is numeric we will no longer enforce it to be in the future to better handle clients with skewed clocks.

Remove check that IAT claim must be in the future

---

src/Auth0.Core/Http/ApiConnection.cs
tests/Auth0.ManagementApi.IntegrationTests/ApiConnectionTests.cs

ApiConnection in Auth0 versions 6.x adds DefaultRequestsHeader to HttpClient every time it is created.
It causes issues in environments that use a single HttpClient, headers collections keeps growing an eventually causes `400 Request Header Or Cookie Too Large` from Auth0 and other servers that HttpClient is used for. It is a significant production issue for us.
This PR makes change to replace the default `Auth0-Client` header instead of keep adding one.
This PR is based on #6.5.5 release tag, since there's no version 6.x branch, I could only chose `master` as PR base.
The real delta: https://github.com/auth0/auth0.net/pull/358/commits/30cebe53dab4e8f4abad89f0a40a96c4f3b23476
- I didn't end up creating an issue, ticket, etc. …

Fix ApiConnection adds the default HttpHeader to HttpClient even if it exists

---

src/Auth0.ManagementApi/HttpClientManagementConnection.cs

Yes v7.0 works for .Net core application but for .Net framework, it doesn't work.
If you look over the code, SendRequest is a task and after that using statements ends which actually disposing the request. After dispose of request, task SendRequest executes where request object is needed for "var response = await httpClient.SendAsync(request).ConfigureAwait(false);"
using (var request = new HttpRequestMessage(HttpMethod.Get, uri))
{
ApplyHeaders(request.Headers, headers);
return SendRequest<T>(request, converters);
}
- Endpoints added, deleted, deprecated, or changed
- Classes and methods added, deleted, deprecated, or changed
- Screenshots of new or changed UI, if applicable
- A summary of usage if this is a new …

issue #366 solved for .Net framework applications

---

src/Auth0.AuthenticationApi/HttpClientAuthenticationConnection.cs
src/Auth0.ManagementApi/HttpClientManagementConnection.cs

`ConfigureAwait(false)` was missing in a couple of places in `HttpClientAuthenticationConnection` and `HttpClientManagementConnection`.

Add missing ConfigureAwait(false) to HttpClient*Connection Get/Send

---

src/Auth0.ManagementApi/Clients/BaseClient.cs
src/Auth0.ManagementApi/Clients/ClientGrantsClient.cs
src/Auth0.ManagementApi/Clients/ClientsClient.cs
src/Auth0.ManagementApi/Clients/ConnectionsClient.cs
src/Auth0.ManagementApi/Clients/CustomDomainsClient.cs
src/Auth0.ManagementApi/Clients/DeviceCredentialsClient.cs
src/Auth0.ManagementApi/Clients/GuardianClient.cs
src/Auth0.ManagementApi/Clients/JobsClient.cs
src/Auth0.ManagementApi/Clients/LogsClient.cs
src/Auth0.ManagementApi/Clients/ResourceServersClient.cs
src/Auth0.ManagementApi/Clients/RolesClient.cs
src/Auth0.ManagementApi/Clients/RulesClient.cs
src/Auth0.ManagementApi/Clients/UserBlocksClient.cs
src/Auth0.ManagementApi/Clients/UsersClient.cs

Path parameters were not being encoded which was specifically causing problems with resource servers which can be referenced by URL.
Fixes #377

Encode all path parameters in the Managment API

---

src/Auth0.AuthenticationApi/Tokens/AsyncAgedCache.cs
tests/Auth0.AuthenticationApi.IntegrationTests/Tokens/AsyncAgedCacheTests.cs

Cache was being incorrectly checked for JWKS keys.

Fix async cache expiration for JWKS

---

tests/Auth0.AuthenticationApi.IntegrationTests/Auth0.AuthenticationApi.IntegrationTests.csproj
tests/Auth0.Core.UnitTests/Auth0.Core.UnitTests.csproj
tests/Auth0.ManagementApi.IntegrationTests/Auth0.ManagementApi.IntegrationTests.csproj

update to asp.net core 3.1. 2.0 - retired more than a 1.5 years ago by microsoft
minor packages update
https://dotnet.microsoft.com/platform/support/policy/dotnet-core

tests to .net core 3.1

---

src/Auth0.AuthenticationApi/HttpClientAuthenticationConnection.cs
src/Auth0.ManagementApi/HttpClientManagementConnection.cs

It is possible to change the default settings for JSON.NET at a global level. We want to ensure we do not pick up any global settings to ensure deserialization works as we expect.
Fixes #390

Do not use JSON.NET's default serializer settings

---

src/Auth0.AuthenticationApi/AuthenticationApiClient.cs
src/Auth0.AuthenticationApi/Models/PasswordlessEmailRequest.cs
src/Auth0.AuthenticationApi/Models/PasswordlessEmailResponse.cs
src/Auth0.AuthenticationApi/Models/PasswordlessSmsRequest.cs
tests/Auth0.AuthenticationApi.IntegrationTests/Auth0.AuthenticationApi.IntegrationTests.csproj
tests/Auth0.AuthenticationApi.IntegrationTests/PasswordlessTests.cs
tests/Auth0.ManagementApi.IntegrationTests/TestBase.cs

Adds support for `client_secret` being sent as a new parameter to `passwordless/start`
https://community.auth0.com/t/passwordless-connection-not-working-for-tenants-created-after-jan-2-2020/36415
Basic change is very simple but also fixed return `id` and added `email_verified` on the response.
Tests are now conditionally skippable depending on whether the environment variables are set.

Add client secret to passwordless

---

src/Auth0.AuthenticationApi/AuthenticationApiClient.cs
tests/Auth0.AuthenticationApi.IntegrationTests/Builders/UriBuildersTests.cs

Right now if you pass a URL to AuthenticationApiClient the path portion is ignored.
While this is never an issue in real-world usage it does prevent some development and testing scenarios from being able to mock out the server-side.
This is a potentially breaking change if a customer today was accidentally passing a URL that incorrectly contained a path parameter but that is an unlikely scenario so not treating this as a breaking change under the "semver is an intent" philosophy.

Preserve URL path for auth

---

tests/Auth0.ManagementApi.IntegrationTests/StatsTests.cs

The stats tests fail if there's been little to no activity. 
Extending the daily stats out to -100 gives the daily stats test some more leeway before failure.
The active users test still fails even though sometimes it passes. The activity of the tests themselves if processed quickly enough can cause the 0 to be 1. Right now though it doesn't seem to be the case so is being skipped.

Skip unreliable stats test

---

src/Auth0.ManagementApi/Clients/LogStreamsClient.cs
src/Auth0.ManagementApi/Clients/LogsClient.cs
src/Auth0.ManagementApi/ManagementApiClient.cs
src/Auth0.ManagementApi/Models/LogStream.cs
src/Auth0.ManagementApi/Models/LogStreamBase.cs
src/Auth0.ManagementApi/Models/LogStreamCreateRequest.cs
src/Auth0.ManagementApi/Models/LogStreamStatus.cs
src/Auth0.ManagementApi/Models/LogStreamType.cs
src/Auth0.ManagementApi/Models/LogStreamUpdateRequest.cs
src/Auth0.ManagementApi/Models/LogStreamUpdateStatus.cs
tests/Auth0.ManagementApi.IntegrationTests/LogStreamsTests.cs
tests/Auth0.ManagementApi.IntegrationTests/Readme.md
tests/Auth0.ManagementApi.IntegrationTests/TestBase.cs

This PR adds support for the [Auth0 Log Streams API](https://auth0.com/docs/api/management/v2#!/Log_Streams/get_log_streams).
API:
```csharp
// Create a new stream
var createdLogStream = await client.LogStreams.CreateAsync(new LogStreamCreateRequest
{
Name = "My Log Stream",
Type = LogStreamType.Http,
Sink = new
{
httpEndpoint = "https://my-stream.com",
httpContentType = "application/json",
httpContentFormat = "JSONOBJECT",
httpAuthorization = "http-auth"
}
});
// Get a stream by ID
var stream = await client.LogStreams.GetAsync(createdLogStream.Id);
// Update it
var updatedStream = await client.LogStreams.UpdateAsync(new LogStreamUpdateRequest
{
Name = "New stream name",
Status = LogStreamStatus.Paused,
Sink = new
{
httpEndpoint = "https://new-stream-endpoint.com"
}
};
// Delete a stream …
```

[SDK-1871] Add Management API support for Log Streams

---

src/Auth0.ManagementApi/Models/EmailVerificationIdentity.cs
src/Auth0.ManagementApi/Models/EmailVerificationTicketRequest.cs
src/Auth0.ManagementApi/Models/VerifyEmailJobRequest.cs
tests/Auth0.ManagementApi.IntegrationTests/JobsTest.cs
tests/Auth0.ManagementApi.IntegrationTests/TicketsTests.cs

Add support for specifying the identity property when calling `jobs/verification-email` and `tickets/email-verification`.
- https://auth0.com/docs/api/management/v2#!/Tickets/post_email_verification
- https://auth0.com/docs/api/management/v2#!/Jobs/post_verification_email

[SDK-1822] Support new Email Verification Fields

---

src/Auth0.ManagementApi/Clients/ConnectionsClient.cs
tests/Auth0.ManagementApi.IntegrationTests/ConnectionTests.cs

Closes #416
Calling Connections.GetAllSync with multiple strategies at once results in an Exception being thrown because it is trying to add multiple items with the same key to the queryStrings dictionary.
This PR ensures this is supported by giving them the correct key (`Strategy[0]`, Strategy[1]`)
https://github.com/auth0/auth0.net/issues/416

[SDK-2003] Support multiple Strategies in Connections.GetAllAsync

---

docs-source/migrating-to-v7.md
docs/migrating-to-v7.html

V7 requires the use of openid scope but it is not listed as part of the migration page.
https://github.com/auth0/auth0.net/issues/372

[SDK-1980] Add openid scope requirement to migrating to v7

---

src/Auth0.ManagementApi/Clients/UsersClient.cs
src/Auth0.ManagementApi/Models/PermissionSource.cs
src/Auth0.ManagementApi/Models/PermissionSourceType.cs
src/Auth0.ManagementApi/Models/UserPermission.cs
tests/Auth0.ManagementApi.IntegrationTests/UsersTests.cs

`UsersClient` now returns permissions along with the source of the permissions, according to apparent API specifications. This is done by simply updating the types to pass the permission sources from the http API to the client of this library.
Tests received a minor update to include this change.
This is a response to issue #424.
This minor change has only been included on the existing test that calls `UsersClient.GetPermissions`. As I don't believe I have access to the underlying definition of the API, please let me know if there are any differences between this implementation and the underlying API.
> This reflects personal testing on the Management API through the portal, and has been tested in my local project, not sure what else I can do.
(I can't test this without merging …

Adds permission sources to User Response

---

src/Auth0.AuthenticationApi/AuthenticationApiClient.cs
src/Auth0.AuthenticationApi/IAuthenticationApiClient.cs
src/Auth0.AuthenticationApi/Models/PasswordlessEmailTokenRequest.cs
src/Auth0.AuthenticationApi/Models/PasswordlessSmsTokenRequest.cs
src/Auth0.AuthenticationApi/Models/PasswordlessTokenRequestBase.cs
tests/Auth0.AuthenticationApi.IntegrationTests/Auth0.AuthenticationApi.IntegrationTests.csproj
tests/Auth0.AuthenticationApi.IntegrationTests/PasswordlessTests.cs

Currently, the API allows to start the passwordless flow to retrieve a OTP. However, the API does not allow for anyone to exchange that OTP for Token(s). 
This PR adds this possibility by adding an overload for the GetTokenAsync method for both Passwordless With Email and SMS.
https://github.com/auth0/auth0.net/issues/419
Please describe how this can be tested by reviewers. Be specific about anything not tested and reasons why. If this library has unit and/or integration testing, tests should be added for new functionality and existing tests should complete without errors. 
Adding integration tests for this wasn't possible, so I added a unit test to verify the correct request is being sent.

[SDK-2005]: Complete passwordless API

---

CHANGELOG.md
build/common.props
package-lock.json
package.json
scripts/changelog.js
scripts/cleanup.js
scripts/exec.js
scripts/release.js
scripts/version.js

This also fixes SDK-2091 to change the way we handle changelogs
As of this PR, the changelog is automatically generated using node scripts.
Even thought it might be a bit weird to be adding package.json and a bunch of node scripts to the .NET repository, it does ensure change log generation is close to identical to how it is done within our JavaScript SDKs.

Prepare Release 7.3.0

---

.github/stale.yml

Ensure only issues that are waiting for customers are marked as stale

Only label "waiting for customer" is marked stale

---

docs/api/Auth0.ManagementApi.Models.GuardianFactorName.html
src/Auth0.ManagementApi/Models/GuardianFactorName.cs
tests/Auth0.ManagementApi.IntegrationTests/GuardianTests.cs

- Added missing factor name's: https://auth0.com/docs/api/management/v2#!/Guardian/get_factors
- fixed a test that is currently broken on master since an update to Auth0's available factories.
#445

Include WebAuthn Guardian Factory names

---

src/Auth0.ManagementApi/Models/ClientBase.cs
src/Auth0.ManagementApi/Models/RefreshToken.cs
src/Auth0.ManagementApi/Models/RefreshTokenExpirationType.cs
src/Auth0.ManagementApi/Models/RefreshTokenRotationType.cs
tests/Auth0.ManagementApi.IntegrationTests/ClientTests.cs

I added new models for the refresh token rotation. With the changes it should be possible to configure
refresh token settings on create and update of clients.
This is important, because at the moment it is impossible to configure a client for refresh token rotation.
I added the properties as described in the api documentation: https://auth0.com/docs/api/management/v2?utm_source=emea-google-dg&utm_medium=cpc&utm_campaign=Branded&utm_content=dynamicRT2&utm_term=&gclid=Cj0KCQiA-rj9BRCAARIsANB_4ADez090wM_osbvalReSynvXe2yRi80CsGig9CxckDToVUFjizzbPukaAnZ3EALw_wcB#!/Clients/post_clients
I was not able to run integration tests, because i do not have a tenant to use.

Allow creating and updating RefreshToken settings for Clients

---

src/Auth0.ManagementApi/Models/GetUsersRequest.cs

According to the docs of API v2 (https://auth0.com/docs/api/management/v2#!/Users/get_users), Connection is only taken into account when using SearchEngine v1, this was not reflected in our API docs.
Closes #466

Update Docs for GetUsersRequest regarding Connection and SearchEngine

---

src/Auth0.ManagementApi/Models/TenantFlags.cs
tests/Auth0.ManagementApi.IntegrationTests/TenantSettingsTests.cs

The PR syncs the TenantFlags class with the available flags on the API v2 based on https://auth0.com/docs/api/management/v2#!/Tenants/get_settings
Closes #465

Sync Tenant Flags with API v2

---

tests/Auth0.AuthenticationApi.IntegrationTests/Auth0.AuthenticationApi.IntegrationTests.csproj
tests/Auth0.Core.UnitTests/Auth0.Core.UnitTests.csproj
tests/Auth0.ManagementApi.IntegrationTests/Auth0.ManagementApi.IntegrationTests.csproj

This PR updates the test projects to use .NET 5 so we can use .NET 5 on the CI server, This also avoids the need to install two SDKs on our build server.

Use .NET 5 for test projects

---

src/Auth0.AuthenticationApi/Tokens/IdTokenValidator.cs
src/Auth0.AuthenticationApi/Tokens/JsonWebKeys.cs
src/Auth0.Core/Exceptions/ApiException.cs

Our SDK is using `ConfigureAwait(false)` on all `await` calls except for these 3.
Normally, when using async code, the next code is executed on the calling thread. However, in a library that shouldn't be required, so avoiding that has some improvements in terms of performance and deadlocks. Avoiding that can be done by using `ConfigureAwait(false)`.
Adding some text from https://devblogs.microsoft.com/dotnet/configureawait-faq/
> ConfigureAwait(continueOnCapturedContext: false) is used to avoid forcing the callback to be invoked on the original context or scheduler. This has a few benefits:
> 
> **Improving performance**. There is a cost to queueing the callback rather than just invoking it, both because there’s extra work (and typically extra allocation) involved, but also because it …

Ensure await is using ConfigureAwait

---

tests/Auth0.ManagementApi.IntegrationTests/GuardianTests.cs

Our CI has been failing for a while because of a misconfigured test that tests the Guardian Factors where it expected 6 factors while it should be 7.

Change Guardian Factors test to expect 7 instead of 6 factors

---

docs-source/index.md
src/Auth0.AuthenticationApi/AuthenticationApiClient.cs
src/Auth0.AuthenticationApi/Builders/AuthorizationUrlBuilder.cs
src/Auth0.AuthenticationApi/Models/AuthorizationCodeRequestBase.cs
src/Auth0.AuthenticationApi/Models/RefreshTokenRequest.cs
src/Auth0.AuthenticationApi/Tokens/Auth0ClaimNames.cs
src/Auth0.AuthenticationApi/Tokens/IdTokenClaimValidator.cs
src/Auth0.AuthenticationApi/Tokens/IdTokenRequirements.cs
tests/Auth0.AuthenticationApi.IntegrationTests/Builders/UriBuildersTests.cs

This PR adds support for Organizations and user invitation:
- Allow to specify `organization` and `invitation` parameters when building the Authorize URL
- Allow to pass the `organization` to `GetTokenAsync` when called for either `AuthorizationCodePkceTokenRequest`, `AuthorizationCodeTokenRequest` or `RefreshTokenRequest`. Doing so will ensure the `org_id` claim in the retrieved ID Token is validated against the provided `organization` value.
- Update the docs to show how `organization` and `invitation` can be configured when using the AuthorizeUrlBuilder
- Adds a note on the fact that the exact same `organization` value should be configured when using either `AuthorizationCodePkceTokenRequest`, `AuthorizationCodeTokenRequest` or `RefreshTokenRequest`

[SDK-2400] Add support for Organizations

---

src/Auth0.ManagementApi/Models/GuardianFactor.cs
src/Auth0.ManagementApi/Models/GuardianFactorName.cs
tests/Auth0.ManagementApi.IntegrationTests/GuardianTests.cs

Both our SDK (at least the `Guardian.GetFactorsAsync();` method) and our tests are broken as Auth0 Server supports another Factor Name that can not be mapped to our enum.
Ideally, we wouldn't use an enum here (but use a string instead) to be able to always map any new factor name, but that would be a breaking change.
This PR ensures the code doesn't break at run time, setting the `name` to `null` when it can not map it. 
It also fixes the tests for now, however, our tests would still fail when a new one gets added so we should catch this ourselves rather fast and update our enum.

Make GuardianFactor serialization a bit more resilient to new factor names

---

src/Auth0.AuthenticationApi/AuthenticationApiClient.cs

ClientSecret is not set when using PKCE, however this is required when using PKCE from a Web Application such as ASP.NET MVC.

Set ClientSecret if defined when using PKCE

---

src/Auth0.ManagementApi/Models/CustomDomainVerification.cs
src/Auth0.ManagementApi/Models/CustomDomainVerificationMethod.cs

The Methods property on the CustomDomainVerification type was defined as an array of strings, while its actually an array of objects, see https://auth0.com/docs/api/management/v2#!/Custom_Domains/get_custom_domains.
This PR doesn't add tests as we already have a test in place for this, but its configured to only run manually. I manually run the test to verify it works as expected now.
Fixes #508

Ensure CustomDomainVerification.Methods can be serialized

---

src/Auth0.ManagementApi/Models/OrganizationConnection.cs
src/Auth0.ManagementApi/Models/OrganizationConnectionInfo.cs

The `Connection` property was missing on the `OrganizationConnection`, but it is returned with the following responses:
- https://auth0.com/docs/api/management/v2#!/Organizations/get_enabled_connections
- https://auth0.com/docs/api/management/v2#!/Organizations/post_enabled_connections
- https://auth0.com/docs/api/management/v2#!/Organizations/get_enabled_connections_by_connectionId
- https://auth0.com/docs/api/management/v2#!/Organizations/patch_enabled_connections_by_connectionId
Closes #502

Add connection property to OrganizationConnection

---

tests/Auth0.AuthenticationApi.IntegrationTests/AccessTokenTests.cs
tests/Auth0.AuthenticationApi.IntegrationTests/AuthenticationTests.cs
tests/Auth0.AuthenticationApi.IntegrationTests/Tokens/IdTokenValidatorIntegrationTests.cs
tests/Auth0.ManagementApi.IntegrationTests/BrandingClientTests.cs
tests/Auth0.ManagementApi.IntegrationTests/ClientGrantTests.cs
tests/Auth0.ManagementApi.IntegrationTests/ClientTests.cs
tests/Auth0.ManagementApi.IntegrationTests/ConnectionTests.cs
tests/Auth0.ManagementApi.IntegrationTests/EmailProviderTests.cs
tests/Auth0.ManagementApi.IntegrationTests/EmailTemplatesTests.cs
tests/Auth0.ManagementApi.IntegrationTests/GuardianTests.cs
tests/Auth0.ManagementApi.IntegrationTests/HooksTests.cs
tests/Auth0.ManagementApi.IntegrationTests/JobsTest.cs
tests/Auth0.ManagementApi.IntegrationTests/LoadTests.cs
tests/Auth0.ManagementApi.IntegrationTests/LogStreamsTests.cs
tests/Auth0.ManagementApi.IntegrationTests/LogsTests.cs
tests/Auth0.ManagementApi.IntegrationTests/OrganizationTests.cs
tests/Auth0.ManagementApi.IntegrationTests/ResourceServerTests.cs
tests/Auth0.ManagementApi.IntegrationTests/RolesTests.cs
tests/Auth0.ManagementApi.IntegrationTests/RulesTests.cs
tests/Auth0.ManagementApi.IntegrationTests/StatsTests.cs
tests/Auth0.ManagementApi.IntegrationTests/TenantSettingsTests.cs
tests/Auth0.ManagementApi.IntegrationTests/TicketsTests.cs
tests/Auth0.ManagementApi.IntegrationTests/UserBlockTests.cs
tests/Auth0.ManagementApi.IntegrationTests/UsersTests.cs

Ensure our tests use more retries to ensure we don't hit rate limits.
Also excluded two tests that appear to be problematic, will look into re-enabling soon.

Avoid rate limits in tests

---

src/Auth0.ManagementApi/Clients/OrganizationsClient.cs
tests/Auth0.ManagementApi.IntegrationTests/OrganizationTests.cs

When querying the management api for organisation member roles via mgmtClient.Organizations.GetAllMemberRolesAsync, the return type is OrganizationMember instead of Role. The result is a mapping with the role name but no other role information. 
GetAllMemberRolesAsync should return a type of Role and not OrganizationMember

GetAllMemberRolesAsync should return a list of Role instances

---

src/Auth0.ManagementApi/Paging/CheckpointPagedListConverter.cs
tests/Auth0.ManagementApi.IntegrationTests/RolesTests.cs

Checkpoint pagination calls weren't returning the results when no `next` property is returned in the response, breaking all last pages.
This PR ensures it returns the data as expected.

Ensure Checkpoint Pagination works when no next is returned

---

docs/api/Auth0.AuthenticationApi.AuthenticationApiClient.html
src/Auth0.AuthenticationApi/AuthenticationApiClient.cs

The generated docs for AuthenticationApiClient has an incorrect code snippet, as it is missing a constructor argument.
Closes #523

Add missing constructor Argument to AuthenticationApiClient docs

---

src/Auth0.ManagementApi/Clients/ClientGrantsClient.cs
src/Auth0.ManagementApi/Clients/ClientsClient.cs
src/Auth0.ManagementApi/Clients/ConnectionsClient.cs
src/Auth0.ManagementApi/Clients/DeviceCredentialsClient.cs
src/Auth0.ManagementApi/Clients/HooksClient.cs
src/Auth0.ManagementApi/Clients/LogsClient.cs
src/Auth0.ManagementApi/Clients/ResourceServersClient.cs
src/Auth0.ManagementApi/Clients/RulesClient.cs
src/Auth0.ManagementApi/Clients/UsersClient.cs
tests/Auth0.ManagementApi.IntegrationTests/ClientGrantTests.cs
tests/Auth0.ManagementApi.IntegrationTests/ClientTests.cs
tests/Auth0.ManagementApi.IntegrationTests/HooksTests.cs
tests/Auth0.ManagementApi.IntegrationTests/LogsTests.cs
tests/Auth0.ManagementApi.IntegrationTests/ResourceServerTests.cs
tests/Auth0.ManagementApi.IntegrationTests/RulesTests.cs
tests/Auth0.ManagementApi.IntegrationTests/UsersTests.cs

Some of the endpoints on API v2 have support for requests without pagination. This PR ensures those methods are callable without specifying an instance of `PaginationInfo`. 
https://auth0.com/docs/api/management/v2
Closes #495

[SDK-2548] Support unpaginated requests for some endpoints

---

tests/Auth0.AuthenticationApi.IntegrationTests/DatabaseConnectionTests.cs
tests/Auth0.AuthenticationApi.IntegrationTests/DeviceCodeTests.cs

Using TestAuthenticationApiClient would retry calls when getting Rate Limit Exceptions.

Use TestAuthenticationApiClient in tests

---

CHANGELOG.md
build/common.props
docs/api/Auth0.ManagementApi.Models.EnrollmentAuthMethod.html
docs/api/Auth0.ManagementApi.Models.EnrollmentsResponse.html
docs/manifest.json
docs/xrefmap.yml

**Changed**
- Increase delay between subsequent retries [\#540](https://github.com/auth0/auth0.net/pull/540) ([frederikprijck](https://github.com/frederikprijck))
**Fixed**
- add webauthn-* enrollment auth methods [\#539](https://github.com/auth0/auth0.net/pull/539) ([frederikprijck](https://github.com/frederikprijck))
- Support updating all guardian factors [\#536](https://github.com/auth0/auth0.net/pull/536) ([frederikprijck](https://github.com/frederikprijck))

Release 7.12.1

---

src/Auth0.ManagementApi/Clients/GuardianClient.cs
src/Auth0.ManagementApi/Models/GuardianPhoneMessageTypes.cs
tests/Auth0.ManagementApi.IntegrationTests/GuardianTests.cs

Implements missing methods to retrieve and update the Enabled Phone Factors for MFA.
Docs:
- https://auth0.com/docs/api/management/v2#!/Guardian/get_message_types
- https://auth0.com/docs/api/management/v2#!/Guardian/put_message_types
- https://auth0.com/docs/secure/multi-factor-authentication/multi-factor-authentication-factors/configure-sms-voice-notifications-mfa#use-the-management-api
Closes #528 

[SDK-3104] Retrieve and Update the Enabled Phone Factors

---

src/Auth0.AuthenticationApi/AuthenticationApiClient.cs
src/Auth0.AuthenticationApi/Models/DeviceCodeTokenRequest.cs
src/Auth0.AuthenticationApi/Models/PasswordlessTokenRequestBase.cs

Our SDK validates ID Tokens for all but 3 method calls:
- Device Code
- Passwordless with Email
- Passwordless with SMS
We should align the validation here and ensure the above methods also validate the ID Token.
Note that this is technically a breaking change ... Anyone retrieving an Invalid ID Token will be able to use the methods today, while after this change they suddenly get an exception when calling one of these methods.
However, I would argue this should be fine to release in a **minor version**, as anyone that we break here is made aware of the incorrect ID Token usage. When needed, they can still rollback to a version prior to this change if they need a fix ASAP and then circle back on fixing their incorrect ID Tokens. But regardless I would argue we want to push them into …

[SDK-3172] Add ID Token validation to device-code and passwordless

---

CHANGELOG.md
build/common.props
docs/api/Auth0.AuthenticationApi.AuthenticationApiClient.html
docs/api/Auth0.AuthenticationApi.Models.DeviceCodeTokenRequest.html
docs/api/Auth0.AuthenticationApi.Models.PasswordlessTokenRequestBase.html
docs/api/Auth0.ManagementApi.Clients.BaseClient.html
docs/api/Auth0.ManagementApi.Clients.RulesConfigClient.html
docs/api/Auth0.ManagementApi.Clients.html
docs/api/Auth0.ManagementApi.ManagementApiClient.html
docs/api/Auth0.ManagementApi.Models.RulesConfig.html
docs/api/Auth0.ManagementApi.Models.RulesConfigCreateOrUpdateRequest.html
docs/api/Auth0.ManagementApi.Models.html
docs/api/toc.html
docs/manifest.json
docs/xrefmap.yml

**Added**
- Add support for Rules Configs endpoints  [\#552](https://github.com/auth0/auth0.net/pull/552) ([caldwell0414](https://github.com/caldwell0414))
**Changed**
- Add ID Token validation to device-code and passwordless  [\#553](https://github.com/auth0/auth0.net/pull/553) ([frederikprijck](https://github.com/frederikprijck))
**Note** that with this release, ID Token validation has been added when retrieving a token using any of the Device Code or Passwordless flows.
There might be a rare occasion where this could break your application, in the situation where you are using invalid ID Tokens.
However, typically this should not cause any issues as ID Tokens are supposed to be valid. If they aren't, you probably want to get notified about it as soon as possible.
Prior to this change, …

Release 7.15.0

---

src/Auth0.ManagementApi/Clients/RulesConfigClient.cs
src/Auth0.ManagementApi/HttpClientManagementConnection.cs

Adds a few missing XML comments, and fixes one that was incorrectly using `id` instead of `key`.

Fix warnings regarding XML comments

---

src/Auth0.ManagementApi/Models/Connection.cs

Added ProvisioningTicketUrl to Connection class.  ProvisioningTicketUrl (provisioning_ticket_url) is returned when getting connections of with specific strategies, including 'google-apps'.

Add ProvisioningTicketUrl

---

.shiprc
build/common.props

This prepares the project to use ship:
- ensure ship can replace the version in csproj by using a single Version property
- add shiprc

[SDK-3401] Prepare project to integrate ship

---

docs/api/Auth0.ManagementApi.Models.OrganizationInvitation.html
src/Auth0.ManagementApi/Models/OrganizationInvitation.cs

The Id property on the OrganizationInvitation object has the summary "The ID of the organization". It should be "The ID of the ticket".
[- support ticket](https://github.com/auth0/auth0.net/issues/570)
Not required as documentation change only.

Correct description OrganizationInvitation Id

---

src/Auth0.ManagementApi/Models/Connection.cs

As `DisplayName` is now defined on `ConnectionBase` (see #572), it should not be defined on `Connection`.
#572

Remove DisplayName from Connection as it exists on ConnectionBase

---

tests/Auth0.IntegrationTests.Shared/Auth0.IntegrationTests.Shared.csproj

Signs the Auth0.IntegrationTests.Shared project to avoid console warnings:

Sign Auth0.IntegrationTests.Shared to avoid console warnings

---

src/Auth0.ManagementApi/Models/OrganizationCreateRequest.cs

- added property in OrganizationCreateRequest model

Support EnabledConnections in OrganizationCreateRequest

---

src/Auth0.ManagementApi/Models/AttackProtection/BreachedPasswordDetection.cs
tests/Auth0.ManagementApi.IntegrationTests/AttackProtectionTests.cs

Adds support for the `stages` property on Breached Password Detection configuration. Similar to Suspicious IP Throttling this is used to configured the `shields` applied at different stages. Currently only `pre-user-registration` is supported 
See linked tickets on SDK-3641

[SDK-3641] Support stage property in Breached Password Detection configuration

---

src/Auth0.ManagementApi/Models/TenantSettingsBase.cs
tests/Auth0.ManagementApi.IntegrationTests/TenantSettingsTests.cs

Adds support for `session_cookie` on the `/tenant/settings` endpoint.
https://auth0.com/docs/api/management/v2#!/Tenants/tenant_settings_route

[SDK-2557] Add support for Ephemeral sessions

---

Auth0.Net.sln

The path has been updated for .NET6.

Fix incorrect path to Auth0.NET6 playground

---

src/Auth0.AuthenticationApi/AuthenticationApiClient.cs
src/Auth0.AuthenticationApi/Tokens/IdTokenValidator.cs
src/Auth0.AuthenticationApi/Tokens/JsonWebKeyCache.cs
src/Auth0.AuthenticationApi/Tokens/JsonWebKeys.cs
src/Auth0.AuthenticationApi/Tokens/OpenIdConnectDocumentRetriever.cs
tests/Auth0.AuthenticationApi.IntegrationTests/Tokens/IdTokenValidatorIntegrationTests.cs

When using the SDK with a proxy, there is no way for the call to retrieve the `openid-configuration` to use that same proxy. This PR updates the internals of the SDK in such a way that it reuses the same `IAuthenticationConnection` implementation that's used by the `AuthenticationApiClient`.
Closes #567

Rework IdTokenValidator to be able to use a proxy

---

src/Auth0.ManagementApi/Clients/ConnectionsClient.cs
src/Auth0.ManagementApi/Clients/IConnectionsClient.cs

Adds the connection status check API as I noticed it was missing from the connections client.
https://auth0.com/docs/api/management/v2#!/Connections/get_status
Not sure of a good way of adding tests for this, as a valid AD or LDAP connection would need to be setup on the Auth0 side.

Add support for the connection status API

---

tests/Auth0.ManagementApi.IntegrationTests/JobsTest.cs
tests/Auth0.ManagementApi.IntegrationTests/OrganizationTests.cs
tests/Auth0.ManagementApi.IntegrationTests/TicketsTests.cs
tests/Auth0.ManagementApi.IntegrationTests/UsersTests.cs

There appears to be a period of eventual consistency when removing a user without removing it from the organization, causing flakey tests. We are now ensuring we first delete them from the organization members.

Update Organization test to remove member correctly

---

src/Auth0.ManagementApi/Auth0.ManagementApi.csproj
src/Auth0.ManagementApi/Clients/IUsersClient.cs
src/Auth0.ManagementApi/Clients/UsersClient.cs
src/Auth0.ManagementApi/Models/Users/AuthenticationMethod.cs
src/Auth0.ManagementApi/Models/Users/AuthenticationMethodBase.cs
src/Auth0.ManagementApi/Models/Users/AuthenticationMethodCreateRequest.cs
src/Auth0.ManagementApi/Models/Users/AuthenticationMethodUpdateRequest.cs
src/Auth0.ManagementApi/Models/Users/AuthenticationMethodsUpdateRequest.cs
tests/Auth0.ManagementApi.IntegrationTests/TenantSettingsTests.cs
tests/Auth0.ManagementApi.IntegrationTests/UsersTests.cs

Add support for the Factor Management Endpoints.
Method | Endpoint | Description
-- | -- | --
GET | [/api/v2/users/{user}/authentication-methods](https://auth0.com/docs/api/management/v2#!/Users/get_authentication_methods) | Gets a list of authentication methods
GET | [/api/v2/users/{user}/authentication-methods/{authentication_method_id}](https://auth0.com/docs/api/management/v2#!/Users/get_authentication_methods_by_authentication_method_id) | Gets an authentication method by ID.
POST | [/api/v2/users/{id}/authentication-methods](https://auth0.com/docs/api/management/v2#!/Users/post_authentication_methods) | Creates an authentication method for a given user.
PUT | [/api/v2/users/{user}/authentication-methods](https://auth0.com/docs/api/management/v2#!/Users/put_authentication_methods) | …

Add Factor Management Endpoints

---

src/Auth0.AuthenticationApi/AuthenticationApiClient.cs
src/Auth0.AuthenticationApi/IAuthenticationApiClient.cs
src/Auth0.AuthenticationApi/Models/RevokeRefreshTokenRequest.cs
tests/Auth0.AuthenticationApi.IntegrationTests/TokenTests.cs

- Endpoints added
- POST /oauth/revoke 
- Classes and methods added
- class:  `RevokeRefreshTokenRequest`
- method: `IAutheticationApiClient.Task<string> RevokeRefreshTokenAsync(RevokeRefreshTokenRequest request, CancellationToken cancellationToken = default)`
- A summary of usage if this is a new feature or change to a public API (this should also be added to relevant documentation once released)
- added support for missing Revoke Refresh Token endpoint
- support ticket:  #616
Added token test to call revoke api

Added revoke refresh token endpoint support

---

src/Auth0.ManagementApi/Clients/DeviceCredentialsClient.cs
src/Auth0.ManagementApi/Clients/IDeviceCredentialsClient.cs

- Endpoints changed
- get device credentials
- Classes and methods changed
- `DeviceCredentialsClient.GetAllAsync` 
- A summary of usage if this is a new feature or change to a public API (this should also be added to relevant documentation once released)
- allow cancel request of get device credentials endpoint. Added support for cancellation token. 

Added cancellation token to device credentials request

---

tests/Auth0.ManagementApi.IntegrationTests/ActionsTests.cs
tests/Auth0.ManagementApi.IntegrationTests/OrganizationTests.cs
tests/Auth0.ManagementApi.IntegrationTests/RetryUtils.cs

Actions and Organization tend to cause some flakyness in our Integration Tests.
This PR adds a retry for situations that cause such flakyness, as they are most likely caused by the fact that the operations are processed async on API2 side, and not processed in time.

Add retry in Actions en Organizations

---

tests/Auth0.ManagementApi.IntegrationTests/ActionsTests.cs

Follow up on #623 to add an additional retry before deploying an action

Wait for action to be built before trying to deploy

---

src/Auth0.ManagementApi/Models/EmailVerificationTicketRequest.cs
tests/Auth0.ManagementApi.IntegrationTests/TicketsTests.cs

The `ClientId` property was added to the `EmailVerificationTicketRequest.cs` class. This will allow the correct app name to be displayed in the "Go back to <app name>" button once the link has been clicked rather than showing the name "All Applications".
- The issue that I created describing this issue:  #628 
I have added a small integration test based on what was already in the `TicketTests` class. I was able to run the unit tests locally and they all passed but unfortunately I was unable to get the integration tests running. I'm hoping that the integration tests are run in CI/CD though, so we can check that all the tests pass there.

Add ClientId to EmailVerificationTicket

---

tests/Auth0.AuthenticationApi.IntegrationTests/Tokens/SymmetricSignedDecoderTests.cs

Use a dummy secret for testing the SymmetricSignedDecoder.

Update SymmetricSignedDecoderTests to use dummy secret

---

src/Auth0.AuthenticationApi/Models/AuthorizationCodeRequestBase.cs
src/Auth0.AuthenticationApi/Models/RefreshTokenRequest.cs
src/Auth0.AuthenticationApi/Tokens/Auth0ClaimNames.cs
src/Auth0.AuthenticationApi/Tokens/IdTokenClaimValidator.cs
src/Auth0.AuthenticationApi/Tokens/IdTokenRequirements.cs
src/Auth0.AuthenticationApi/Tokens/JwtTokenFactory.cs
tests/Auth0.AuthenticationApi.IntegrationTests/Tokens/IdTokenClaimValidatorTests.cs

Adds support for the organization name by extending the ID Token validation as follows:
- If organization is set and has the `org_` prefix, we expect an org_id claim
- If organization is set and does not have the `org_` prefix, we expect an org_name claim

Support Organization Name

---

src/Auth0.ManagementApi/Auth0.ManagementApi.csproj
src/Auth0.ManagementApi/Clients/GrantsClient.cs
src/Auth0.ManagementApi/Clients/IGrantsClient.cs
src/Auth0.ManagementApi/ManagementApiClient.cs
src/Auth0.ManagementApi/Models/Grants/GetGrantsRequest.cs
src/Auth0.ManagementApi/Models/Grants/Grant.cs
tests/Auth0.ManagementApi.IntegrationTests/GrantsTests.cs

Adds missing Grant endpoints.
Closes #632

Add Grants endpoint

---

src/Auth0.ManagementApi/Models/ClientBase.cs

Adds the missing `cross_origin_authentication` property on Client.
Closes #641

Add cross_origin_authentication on Clients

---

src/Auth0.AuthenticationApi/Models/ChangePasswordRequest.cs

We should be able to sent the Organization parameter when calling `ChangePasswordAsync`.
No documentation on this available yet.

Support providing Organization when resetting password

---

src/Auth0.ManagementApi/Models/UserBase.cs
tests/Auth0.ManagementApi.IntegrationTests/UsersTests.cs

Added generic methods to get/set user metadata, e.g.:
`userInstance.getAppMetadata<MyAppMetadata>();`
`userInstance.getUserMetadata<MyUserMetadata>();`
`userInstance.setAppMetadata(myAppMetadata);`
`userInstance.setUserMetadata(myUserMetadata);`
As for now Newtonsoft.Json.Linq.JObject is used as this type seems to be deserialized when reading users.
Auth0.ManagementApi.Models.UserBase
- added new generic get/set methods for AppMetadata and UserMetadata
Auth0.ManagementApi.IntegrationTests.UsersTests:
- added test for read/write user metadata with new generic get/set methods
#645 
Retrieve a user with AppMetadata, call getAppMetadata with a matching type and see the filled properties
I'm unable to run the tests as configuration seems missing
I'm unable to run the tests as configuration …

added generic get/set metadata methods on UserBase

---

.github/workflows/publish.yml

`dotnet pack` does not allow to pack multiple projects at once, this PR packs every project individually.

Pack every project separatly

---

playground/Auth0.NET6/Properties/launchSettings.json
playground/Auth0.NETCore3/Properties/launchSettings.json
src/Auth0.ManagementApi/Models/Job.cs

Adds the `external_id` property on Job, which can be send when importing users, see https://github.com/auth0/auth0.net/blob/master/src/Auth0.ManagementApi/Clients/JobsClient.cs#L64
Closes #653

Add external_id on Job

---

src/Auth0.ManagementApi/Models/OrganizationGetAllMembersRequest.cs
src/Auth0.ManagementApi/Models/OrganizationMember.cs
tests/Auth0.ManagementApi.IntegrationTests/OrganizationTests.cs

Adds the roles property to the OrganizationMember model as per https://auth0.com/docs/api/management/v2/organizations/get-members

Add roles to OrganizationMember

---

src/Auth0.ManagementApi/Models/Users/AuthenticationMethod.cs

Adds the necessary passkey properties to the AuthenticationMethod model.

Add passkey properties to AuthenticationMethod

---

src/Auth0.ManagementApi/Models/TenantSettingsBase.cs
tests/Auth0.ManagementApi.IntegrationTests/TenantSettingsTests.cs

Adds the new `customize_mfa_in_postlogin_action` tenant setting.

Add customize_mfa_in_postlogin_action to TenantSettings

---

src/Auth0.AuthenticationApi/AuthenticationApiClient.cs
src/Auth0.AuthenticationApi/Models/ClientCredentialsTokenRequest.cs
src/Auth0.ManagementApi/Clients/ClientGrantsClient.cs
src/Auth0.ManagementApi/Clients/IClientGrantsClient.cs
src/Auth0.ManagementApi/Clients/IOrganizationsClient.cs
src/Auth0.ManagementApi/Clients/OrganizationsClient.cs
src/Auth0.ManagementApi/Models/ClientGrantBase.cs
src/Auth0.ManagementApi/Models/ClientGrantUpdateRequest.cs
src/Auth0.ManagementApi/Models/GetClientGrantsRequest.cs
src/Auth0.ManagementApi/Models/OrganizationClientGrant.cs
src/Auth0.ManagementApi/Models/OrganizationCreateClientGrantRequest.cs
src/Auth0.ManagementApi/Models/OrganizationGetClientGrantsRequest.cs
tests/Auth0.AuthenticationApi.IntegrationTests/TokenTests.cs
tests/Auth0.ManagementApi.IntegrationTests/ClientGrantTests.cs

- Adds organization parameter to GetTokenAsync when using ClientCredentials.
- Adds endpoints to get Client Grants for Organizations
- Adds endpoints to get Organizations for ClientGrants
CI won't succeed until the neccesary feature flag is enabled on the testing tenant.

Add Organizations in Client Credentials

---

playground/Auth0.NET6/Auth0.NET6.csproj
playground/Auth0.NETCore3/Auth0.NETCore3.csproj
tests/Auth0.AuthenticationApi.IntegrationTests/Auth0.AuthenticationApi.IntegrationTests.csproj
tests/Auth0.Core.UnitTests/Auth0.Core.UnitTests.csproj
tests/Auth0.ManagementApi.IntegrationTests/Auth0.ManagementApi.IntegrationTests.csproj

Adds explicit depenencies for known vulnerable dependencies to ensure we use versions that are fixed.
```
✗ Denial of Service (DoS) [High Severity][https://security.snyk.io/vuln/SNYK-DOTNET-SYSTEMNETHTTP-60045] in System.Net.Http@4.3.0
introduced by Moq@4.14.7 > Castle.Core@4.4.0 > NETStandard.Library@1.6.1 > System.Net.Http@4.3.0 and 4 other path(s)
This issue was fixed in versions: 4.1.2, 4.3.2
✗ Improper Certificate Validation [High Severity][https://security.snyk.io/vuln/SNYK-DOTNET-SYSTEMNETHTTP-60046] in System.Net.Http@4.3.0
introduced by Moq@4.14.7 > Castle.Core@4.4.0 > NETStandard.Library@1.6.1 > System.Net.Http@4.3.0 and 4 other path(s)
This issue was fixed in versions: 4.1.2, 4.3.2
✗ Privilege Escalation [High Severity][https://security.snyk.io/vuln/SNYK-DOTNET-SYSTEMNETHTTP-600 …
```

Bump dependencies to fix vulnerabilities in tests

---

src/Auth0.AuthenticationApi/AuthenticationApiClient.cs
src/Auth0.AuthenticationApi/Builders/AuthorizationUrlBuilder.cs
src/Auth0.AuthenticationApi/ExtensionMethods.cs
src/Auth0.AuthenticationApi/IAuthenticationApiClient.cs
src/Auth0.AuthenticationApi/Models/PushedAuthorizationRequest.cs
src/Auth0.AuthenticationApi/Models/PushedAuthorizationRequestResponse.cs
src/Auth0.ManagementApi/Models/ClientBase.cs
src/Auth0.ManagementApi/Models/TenantFlags.cs
tests/Auth0.AuthenticationApi.IntegrationTests/PushedAuthorizationRequestTests.cs

Adds support for doing a Pushed Authorization Request in the AuthenticationApiClient, while also adding support for the necessary ManagementApiClient changes.

Add support for Pushed Authorization Request

---

src/Auth0.ManagementApi/Models/BackchannelLogoutInitiators.cs
src/Auth0.ManagementApi/Models/ClientBase.cs
src/Auth0.ManagementApi/Models/ClientResourceServerAssociation.cs
src/Auth0.ManagementApi/Models/LogoutInitiatorModes.cs
src/Auth0.ManagementApi/Models/LogoutInitiators.cs
src/Auth0.ManagementApi/Models/OidcLogoutConfig.cs
tests/Auth0.ManagementApi.IntegrationTests/TestBase.cs

Support for setting Back-Channel Logout URI's and initiators on all clients.
Implement support for Auth0 API endpoints here:
[Back-Channel Logout URI
](https://auth0.com/docs/authenticate/login/logout/back-channel-logout)
I have tested the changes to the SDK and validated they generate valid JSON, i.e.
{"app_type":"native","token_endpoint_auth_method":"client_secret_post","client_metadata":{"Prop1":"1","Prop2":"2"},"is_first_party":true,"name":"int-test C9qIfV3RKUueJGflFsptA","oidc_logout":{"backchannel_logout_urls":["https://logout.com"],"backchannel_logout_initiators":{"mode":"custom","selected_initiators":["rp-logout","idp-logout"]}}}
And
{"app_type":"native","token_endpoint_auth_method":"client_secret_post","client_metadata":{"Prop1":"1","Prop2":"2"},"is_first_party":true,"name":"int-t …

Add OIDC back channel logout

---

src/Auth0.AuthenticationApi/Auth0.AuthenticationApi.csproj
src/Auth0.AuthenticationApi/HttpClientAuthenticationConnection.cs
src/Auth0.Core/Auth0.Core.csproj
src/Auth0.ManagementApi/Auth0.ManagementApi.csproj
src/Auth0.ManagementApi/ManagementApiClient.cs

With the lowest .NET framework currently supported being 4.6.2, it makes sense to remove our 4.5.2 support and only ship .NET Standard 2.0, [which supports 4.6.1 and above](https://learn.microsoft.com/en-us/dotnet/standard/net-standard?tabs=net-standard-2-0).
However, as mentioned [here](https://learn.microsoft.com/en-us/dotnet/standard/library-guidance/cross-platform-targeting), I makes sense to keep an explicit target for .NET 4.6.2 to improve compatibility.
```
CONSIDER adding a target for net462 when you're offering a netstandard2.0 target.
Using .NET Standard 2.0 from .NET Framework has some issues that were addressed in .NET Framework 4.7.2. 
You can improve the experience for developers that are still on .NET Framework 4.6.2 - 4.7.1 by offering them a binary that's built for .NET …
```

Target .NET Framework 4.6.2 instead of 4.5.2

---

src/Auth0.AuthenticationApi/Tokens/AsyncAgedCache.cs
tests/Auth0.AuthenticationApi.IntegrationTests/Tokens/AsyncAgedCacheTests.cs

Once an entry in the AsyncAgedCache is expired, it is not correctly updating the cache. Any subsequent calls will bypass the cache.
This PR ensures expired cache entries are removed from the cache.
Closes #692

Ensure AsyncAgedCache is correctly updated

---

src/Auth0.AuthenticationApi/Models/UserInfo.cs
src/Auth0.Core/Serialization/StringOrObjectAsStringConverter.cs
src/Auth0.ManagementApi/Models/User.cs
tests/Auth0.AuthenticationApi.IntegrationTests/UserInfoDeserializationTests.cs
tests/Auth0.Core.UnitTests/StringOrObjectAsStringConverterTests.cs

Locale is undocumented, and can be a string or an object.
Currently, our SDK defines it as a string, failing deserialisation when an object is provided.
This PR ensures no exception is thrown and deserialization works, but the locale will be a stringified version of the object.

Do not crash when User.Locale and UserInfo.Locale are an object

---

src/Auth0.ManagementApi/Models/OrganizationConnection.cs
src/Auth0.ManagementApi/Models/OrganizationConnectionCreateRequest.cs
src/Auth0.ManagementApi/Models/OrganizationConnectionUpdateRequest.cs
tests/Auth0.ManagementApi.IntegrationTests/OrganizationTests.cs

Adds `show_as_button` to `OrganizationConnection`, `OrganizationConnectionCreateRequest` and `OrganizationConnectionUpdateRequest`. 
This property is documented here:
- [Get connections enabled for an organization](https://auth0.com/docs/api/management/v2/organizations/get-enabled-connections)
- [Add connections to an organization](https://auth0.com/docs/api/management/v2/organizations/post-enabled-connections)
- [Modify an organizations connection](https://auth0.com/docs/api/management/v2/organizations/patch-enabled-connections-by-connection-id)
I have attempted to add a unit test by following the pattern used for `AssignMembershipOnLogin`, however I was not able to run the tests to validate that they passed.

Add show_as_button to organizations connection

---

src/Auth0.ManagementApi/Models/TokenDialect.cs

This PR adds support for new JWT Access Token Profile values in the `/api/v2/resource-servers` endpoint.

[SDK-4773] Support JWT Access Token Profile values in TokenDialect

---

src/Auth0.ManagementApi/Models/OrganizationConnection.cs
src/Auth0.ManagementApi/Models/OrganizationConnectionCreateRequest.cs
src/Auth0.ManagementApi/Models/OrganizationConnectionUpdateRequest.cs
tests/Auth0.ManagementApi.IntegrationTests/OrganizationTests.cs

is_signup_enabled attribute in related to Organisation Connection was not exposed before.
With these changes the users can now :
- Access this attribute in the responses (Create / Update / Get).
- Can use the attribute to set the value during Create and Update.

Adds 'is_signup_enabled' for OrganisationConnection

---

src/Auth0.ManagementApi/Models/OrganizationCreateInvitationRequest.cs
src/Auth0.ManagementApi/Models/OrganizationInvitation.cs
tests/Auth0.ManagementApi.IntegrationTests/OrganizationTests.cs

Ensured the default value for `OrganizationCreateInvitationRequest.SendInvitationEmail` to `True`
Refer #727 for more details.
[Auth0 Docs for CreateInvitations End-point](https://auth0.com/docs/api/management/v2/organizations/post-invitations)

Fixes issue where SendInvitationEmail is not defaulting to True

---

.github/workflows/release.yml
.shiprc
docs-source/docfx.json

- Changes to use `github-actions` for documentation generation and docs deployment.

Generate documentation using docfx in github actions

---

src/Auth0.AuthenticationApi/AuthenticationApiClient.cs
src/Auth0.Core/Utils.cs
src/Auth0.ManagementApi/Clients/BaseClient.cs
src/Auth0.ManagementApi/Clients/ClientsClient.cs
src/Auth0.ManagementApi/Clients/IResourceServersClient.cs
src/Auth0.ManagementApi/Clients/OrganizationsClient.cs
src/Auth0.ManagementApi/Clients/ResourceServersClient.cs
src/Auth0.ManagementApi/Models/ClientBase.cs
src/Auth0.ManagementApi/Models/DefaultOrganization.cs
src/Auth0.ManagementApi/Models/Flows.cs
src/Auth0.ManagementApi/Models/GetClientsRequest.cs
src/Auth0.ManagementApi/Models/OrganizationGetClientGrantsRequest.cs
src/Auth0.ManagementApi/Models/ResourceServerGetRequest.cs
tests/Auth0.Core.UnitTests/UtilsTest.cs
tests/Auth0.ManagementApi.IntegrationTests/ClientGrantTests.cs
tests/Auth0.ManagementApi.IntegrationTests/ClientTests.cs
tests/Auth0.ManagementApi.IntegrationTests/ManagementApiClientTests.cs
tests/Auth0.ManagementApi.IntegrationTests/OrganizationTests.cs
tests/Auth0.ManagementApi.IntegrationTests/ResourceServerTests.cs
tests/Auth0.ManagementApi.IntegrationTests/TestBaseFixture.cs
tests/Auth0.ManagementApi.IntegrationTests/Utils.cs

- Support for Default Organisation in clients
1. Added new field `default_organization` to GET/PATCH endpoints /api/v2/clients/{id} 
2. Added new field `default_organization` to POST endpoints /api/v2/clients/
- Support query param `q` for GET /api/v2/clients
1. `q=client_grant.organization_id:org_sampleorgid213`
2. `q=client_grant.allow_any_organization:true`
- Support query param `grant_ids` for GET /api/v2/organizations/{org_id}/client-grants
- Support query param `identifiers` for GET /api/v2/resource-servers
- [Management API Documentation](https://sus.auth0.com/docs/api/management/v2/organizations/post-organizations)
- [Internal Reference](https://oktawiki.atlassian.net/wiki/spaces/IAMPS/pages/3052704289/Organi …

Organization support for client credentials

---

src/Auth0.ManagementApi/Models/EmailTemplate/EmailTemplateName.cs
tests/Auth0.ManagementApi.IntegrationTests/EmailTemplatesTests.cs

Added the below missing Email Template Types: 
- `verify_email_by_code`
- `reset_email_by_code`
- `user_invitation`
Initial Request -> [ESD-41983](https://auth0team.atlassian.net/browse/ESD-41983)
JIRA - [SDK-5124](https://auth0team.atlassian.net/browse/SDK-5124)
- Extended existing test cases to use the above templates to Create / Update / Patch EmailTemplates.
[ESD-41983]: https://auth0team.atlassian.net/browse/ESD-41983?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SDK-5124]: https://auth0team.atlassian.net/browse/SDK-5124?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Adds missing EmailTemplate types

---

src/Auth0.ManagementApi/Clients/IKeysClient.cs
src/Auth0.ManagementApi/Clients/KeysClient.cs
src/Auth0.ManagementApi/Models/Keys/EncryptionKey.cs
src/Auth0.ManagementApi/Models/Keys/EncryptionKeyCreateRequest.cs
src/Auth0.ManagementApi/Models/Keys/EncryptionKeyGetRequest.cs
src/Auth0.ManagementApi/Models/Keys/EncryptionKeyImportRequest.cs
src/Auth0.ManagementApi/Models/Keys/EncryptionKeyState.cs
src/Auth0.ManagementApi/Models/Keys/EncryptionKeyType.cs
src/Auth0.ManagementApi/Models/Keys/WrappingKey.cs
src/Auth0.ManagementApi/Models/Keys/WrappingKeyCreateRequest.cs
tests/Auth0.AuthenticationApi.IntegrationTests/Testing/ManagementTestBaseUtils.cs
tests/Auth0.IntegrationTests.Shared/CleanUp/CleanUpType.cs
tests/Auth0.IntegrationTests.Shared/CleanUp/EncryptionKeysCleanUpStrategy.cs
tests/Auth0.ManagementApi.IntegrationTests/Auth0.ManagementApi.IntegrationTests.csproj
tests/Auth0.ManagementApi.IntegrationTests/Data/ImportEncryptionKeyResponse.json
tests/Auth0.ManagementApi.IntegrationTests/KeysTests.cs
tests/Auth0.ManagementApi.IntegrationTests/Testing/ManagementTestBaseUtils.cs

Added the following end-points : 
- `GET /api/v2/keys/encryption`
- `POST  /api/v2/keys/encryption`
- `GET  /api/v2/keys/encryption/{kid}`
- `DELETE  /api/v2/keys/encryption/{kid}`
- `POST  /api/v2/keys/encryption/{kid}`
- `POST  /api/v2/keys/encryption/{kid}/wrapping-key`
- [/api/v2/keys/encryption](https://auth0.com/docs/api/management/v2/keys/get-encryption-keys)
- [/api/v2/keys/encryption](https://auth0.com/docs/api/management/v2/keys/post-encryption)
- [/api/v2/keys/encryption/{kid}](https://auth0.com/docs/api/management/v2/keys/get-encryption-key)
- [DELETE  /api/v2/keys/encryption/{kid}](https://auth0.com/docs/api/management/v2/keys/delete-encryption-key)
- [/api/v2/keys/encryption/{kid}](https://auth0.com/docs/api/management/v2/keys/post-encryption-key)
- …

Adds support for BYOK end-points

---

src/Auth0.ManagementApi/Clients/IKeysClient.cs
src/Auth0.ManagementApi/Clients/KeysClient.cs
tests/Auth0.ManagementApi.IntegrationTests/KeysTests.cs

The following endpoints are added : 
- `POST  /api/v2/keys/encryption/rekey`
- [/api/v2/keys/encryption/rekey](https://auth0.com/docs/api/management/v2/keys/post-encryption-rekey)
- JIRA -> [SDK-5126](https://auth0team.atlassian.net/browse/SDK-5126)
The following scenarios have been tested : 
- `Test_rekey_encrypted_keys` : Perform a rekey operation and ensure the Tenant Master Key is rotated. Additionally ensures the original Tenant Master Key is now destroyed.
[SDK-5126]: https://auth0team.atlassian.net/browse/SDK-5126?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Adds support for CYOK end-points

---

src/Auth0.ManagementApi/Clients/ISelfServiceProfilesClient.cs
src/Auth0.ManagementApi/Clients/SelfServiceProfilesClient.cs
src/Auth0.ManagementApi/IManagementApiClient.cs
src/Auth0.ManagementApi/ManagementApiClient.cs
src/Auth0.ManagementApi/Models/SelfServiceProfiles/Branding.cs
src/Auth0.ManagementApi/Models/SelfServiceProfiles/EnabledOrganization.cs
src/Auth0.ManagementApi/Models/SelfServiceProfiles/SelfServiceProfile.cs
src/Auth0.ManagementApi/Models/SelfServiceProfiles/SelfServiceProfileBase.cs
src/Auth0.ManagementApi/Models/SelfServiceProfiles/SelfServiceProfileCreateRequest.cs
src/Auth0.ManagementApi/Models/SelfServiceProfiles/SelfServiceProfileUpdateRequest.cs
src/Auth0.ManagementApi/Models/SelfServiceProfiles/SelfServiceSsoConnectionConfig.cs
src/Auth0.ManagementApi/Models/SelfServiceProfiles/SelfServiceSsoTicket.cs
src/Auth0.ManagementApi/Models/SelfServiceProfiles/SelfServiceSsoTicketCreateRequest.cs
src/Auth0.ManagementApi/Models/SelfServiceProfiles/UserAttribute.cs
tests/Auth0.AuthenticationApi.IntegrationTests/Testing/ManagementTestBaseUtils.cs
tests/Auth0.IntegrationTests.Shared/CleanUp/CleanUpType.cs
tests/Auth0.IntegrationTests.Shared/CleanUp/SelfServiceProviderCleanUpStrategy.cs
tests/Auth0.ManagementApi.IntegrationTests/SelfServiceProfileTest.cs
tests/Auth0.ManagementApi.IntegrationTests/Testing/ManagementTestBaseUtils.cs

- [GET  /api/v2/self-service-profiles](https://auth0.com/docs/api/management/v2/self-service-profiles/get-self-service-profiles)
- [POST  /api/v2/self-service-profiles](https://auth0.com/docs/api/management/v2/self-service-profiles/post-self-service-profiles)
- [GET  /api/v2/self-service-profiles/{id}](https://auth0.com/docs/api/management/v2/self-service-profiles/get-self-service-profiles-by-id)
- [DELETE  /api/v2/self-service-profiles/{id}](https://auth0.com/docs/api/management/v2/self-service-profiles/delete-self-service-profiles-by-id)
- [PATCH  /api/v2/self-service-profiles/{id}](https://auth0.com/docs/api/management/v2/self-service-profiles/patch-self-service-profiles-by-id)
- [GET  /api/v2/self-service-profiles/{id}/custom-text/{language}/{page}](https://auth0.com/docs/api/managemen …

Adds support for Self-Service-Profile endpoints

---

src/Auth0.ManagementApi/Clients/IPromptsClient.cs
src/Auth0.ManagementApi/Clients/PromptsClient.cs
tests/Auth0.ManagementApi.IntegrationTests/PromptsTests.cs

Added the following end points for managing custom-text and partial prompts
- [GET  /api/v2/prompts/{prompt}/custom-text/{language}](https://auth0.com/docs/api/management/v2/prompts/get-custom-text-by-language)
- [PUT  /api/v2/prompts/{prompt}/custom-text/{language}](https://auth0.com/docs/api/management/v2/prompts/put-custom-text-by-language)
- [GET  /api/v2/prompts/{prompt}/partials](https://auth0.com/docs/api/management/v2/prompts/get-partials)
- [PUT  /api/v2/prompts/{prompt}/partials](https://auth0.com/docs/api/management/v2/prompts/put-partials)
- [Auth0 Management SDK Docs](https://auth0.com/docs/api/management/v2/prompts/put-partials)
- JIRA - [SDK-5183](https://auth0team.atlassian.net/browse/SDK-5183)
- Following …

Adds support for managing custom-text and partial-prompts

---

src/Auth0.AuthenticationApi/AuthenticationApiClient.cs
src/Auth0.AuthenticationApi/HttpClientAuthenticationConnection.cs
src/Auth0.AuthenticationApi/IAuthenticationApiClient.cs
src/Auth0.AuthenticationApi/Models/Ciba/ClientInitiatedBackchannelAuthorizationRequest.cs
src/Auth0.AuthenticationApi/Models/Ciba/ClientInitiatedBackchannelAuthorizationResponse.cs
src/Auth0.AuthenticationApi/Models/Ciba/ClientInitiatedBackchannelAuthorizationTokenRequest.cs
src/Auth0.AuthenticationApi/Models/Ciba/ClientInitiatedBackchannelAuthorizationTokenResponse.cs
src/Auth0.AuthenticationApi/Models/Ciba/LoginHint.cs
tests/Auth0.AuthenticationApi.IntegrationTests/ClientInitiatedBackchannelAuthorizationTests.cs

- Added support for Client Initiated Backchannel Authorization.
- A new end-point added for this purpose
- `/bc-authorize`
- A new variant of `GetTokenAsync` Added for fetching the CIBA response.
- JIRA -> [SDK-5208](https://auth0team.atlassian.net/browse/SDK-5208)
Please describe how this can be tested by reviewers. Be specific about anything not tested and reasons why. If this library has unit and/or integration testing, tests should be added for new functionality and existing tests should complete without errors. 
[SDK-5208]: https://auth0team.atlassian.net/browse/SDK-5208?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Adds support for CIBA

---

src/Auth0.ManagementApi/Models/CustomDomain/CustomDomainVerificationResponse.cs

Please describe both what is changing and why this is important. 
- Added `CnameApiKey` property to `CustomDomainVerificationResponse` class to support _self-managed certificates_
- #757
- [POST /custom-domains/:id/verify](https://auth0.com/docs/api/management/v2/custom-domains/post-verify#response-schemas)
Custom domain tests are limited, as described by the [existing tests](https://github.com/auth0/auth0.net/blob/ee4bc1982f26d36585716d9c7a12bf9216f5e8d6/tests/Auth0.ManagementApi.IntegrationTests/CustomDomainsTests.cs), which must be run manually.  Since no other tests exist to test rudimentary serialization, no tests were added.

Adds CnameApiKey to CustomDomainVerificationResponse (#757)

---

src/Auth0.ManagementApi/Clients/CustomDomainsClient.cs
src/Auth0.ManagementApi/Clients/ICustomDomainsClient.cs
src/Auth0.ManagementApi/Models/CustomDomain/CustomDomainBase.cs
src/Auth0.ManagementApi/Models/CustomDomain/CustomDomainCreateRequest.cs
src/Auth0.ManagementApi/Models/CustomDomain/CustomDomainUpdateRequest.cs
tests/Auth0.ManagementApi.IntegrationTests/CustomDomainsTests.cs

- [PATCH  /api/v2/custom-domains/{id}](https://auth0.com/docs/api/management/v2/custom-domains/patch-custom-domains-by-id)
- Added `tls_policy` and `custom_client_ip_header` fields in the models that were missing them.
- [SDK-5495](https://auth0team.atlassian.net/browse/SDK-5495)
Tests for custom domains are limited. We cannot test full CRUD sequence because the tenants allow for only one custom domain and others depend on that domain.
We are therefore limited in scope to what we can test. 
For now, we have updated the test that we run manually to verify that the basic serialization and the GET methods work properly.
[SDK-5495]: …

Add support to Update a Custom Domain

---

src/Auth0.ManagementApi/Clients/FlowsClient.cs
src/Auth0.ManagementApi/Clients/IFlowsClient.cs
src/Auth0.ManagementApi/IManagementApiClient.cs
src/Auth0.ManagementApi/ManagementApiClient.cs
src/Auth0.ManagementApi/Models/Flow/Flow.cs
src/Auth0.ManagementApi/Models/Flow/FlowCreateRequest.cs
src/Auth0.ManagementApi/Models/Flow/FlowExecution.cs
src/Auth0.ManagementApi/Models/Flow/FlowExecutionGetRequest.cs
src/Auth0.ManagementApi/Models/Flow/FlowGetRequest.cs
src/Auth0.ManagementApi/Models/Flow/FlowUpdateRequest.cs
src/Auth0.ManagementApi/Models/Flow/FlowVaultConnection.cs
src/Auth0.ManagementApi/Models/Flow/FlowVaultConnectionCreateRequest.cs
src/Auth0.ManagementApi/Models/Flow/FlowVaultConnectionGetRequest.cs
src/Auth0.ManagementApi/Models/Flow/FlowVaultConnectionUpdateRequest.cs
src/Auth0.ManagementApi/Models/Flow/Hydrate.cs
tests/Auth0.AuthenticationApi.IntegrationTests/Testing/ManagementTestBaseUtils.cs
tests/Auth0.IntegrationTests.Shared/CleanUp/CleanUpType.cs
tests/Auth0.IntegrationTests.Shared/CleanUp/FlowsCleanUpStrategy.cs
tests/Auth0.ManagementApi.IntegrationTests/FlowsTest.cs
tests/Auth0.ManagementApi.IntegrationTests/FormsTest.cs
tests/Auth0.ManagementApi.IntegrationTests/Testing/ManagementTestBaseUtils.cs

Added support for the following end-points
- [GET  /api/v2/flows](https://auth0.com/docs/api/management/v2/flows/get-flows)
- [POST  /api/v2/flows](https://auth0.com/docs/api/management/v2/flows/post-flows)
- [GET  /api/v2/flows/vault/connections](https://auth0.com/docs/api/management/v2/flows/get-flows-vault-connections)
- [POST  /api/v2/flows/vault/connections](https://auth0.com/docs/api/management/v2/flows/post-flows-vault-connections)
- [GET  /api/v2/flows/vault/connections/{id}](https://auth0.com/docs/api/management/v2/flows/get-flows-vault-connections-by-id)
- [DELETE  /api/v2/flows/vault/connections/{id}](https://auth0.com/docs/api/management/v2/flows/delete-flows-vault-connections-by-id)
- [PATCH  /api/v2/flows/vault/connections/{id}](https://auth0.com/docs/api/management/v2/flows/ …

Add support to manage /flows endpoints

---

src/Auth0.ManagementApi/Models/DeviceCredential.cs

A missing field of `UserId` has been added to the `Device Crdential` class. It is documented in the [API documentation](https://auth0.com/docs/api/management/v2/device-credentials/get-device-credentials) but it was missing from the Auth0 SDK.

Added missing user ID field in Device Credentials class

---

src/Auth0.ManagementApi/Clients/GuardianClient.cs
src/Auth0.ManagementApi/Clients/IGuardianClient.cs
src/Auth0.ManagementApi/Models/Guardian/CreateGuardianEnrollmentTicketRequest.cs
src/Auth0.ManagementApi/Models/Guardian/DuoConfiguration.cs
src/Auth0.ManagementApi/Models/Guardian/DuoConfigurationUpdateRequest.cs
src/Auth0.ManagementApi/Models/Guardian/FcmConfiguration.cs
src/Auth0.ManagementApi/Models/Guardian/FcmV1Configuration.cs
src/Auth0.ManagementApi/Models/Guardian/GuardianFactor.cs
src/Auth0.ManagementApi/Models/Guardian/GuardianPhoneEnrollmentTemplate.cs
src/Auth0.ManagementApi/Models/Guardian/PhoneProviderConfiguration.cs
src/Auth0.ManagementApi/Models/Guardian/PushNotificationApnsConfiguration.cs
src/Auth0.ManagementApi/Models/Guardian/PushNotificationApnsConfigurationUpdateRequestBase.cs
tests/Auth0.ManagementApi.IntegrationTests/GuardianTests.cs

Added support for the following end-points : 
- [GET  /api/v2/guardian/factors/duo/settings](https://auth0.com/docs/api/management/v2/guardian/get-factor-duo-settings)
- [PATCH  /api/v2/guardian/factors/duo/settings](https://auth0.com/docs/api/management/v2/guardian/patch-factor-duo-settings)
- [PUT  /api/v2/guardian/factors/duo/settings](https://auth0.com/docs/api/management/v2/guardian/put-factor-duo-settings)
- [GET  /api/v2/guardian/factors/phone/selected-provider](https://auth0.com/docs/api/management/v2/guardian/get-guardian-phone-providers)
- [PUT  /api/v2/guardian/factors/phone/selected-provider](https://auth0.com/docs/api/management/v2/guardian/put-phone-providers)
- [GET  /api/v2/guardian/factors/phone/templates](https://auth0.com/docs/api/management/v2/guardian/get-factor-phone- …

Add support for /guardian end-points

---

src/Auth0.ManagementApi/Clients/GuardianClient.cs
src/Auth0.ManagementApi/Clients/IGuardianClient.cs
src/Auth0.ManagementApi/Models/Guardian/GuardianSnsConfiguration.cs
src/Auth0.ManagementApi/Models/Guardian/PhoneProviderConfiguration.cs
src/Auth0.ManagementApi/Models/Guardian/PushNotificationProviderConfiguration.cs
tests/Auth0.ManagementApi.IntegrationTests/GuardianTests.cs

- Classes and methods added, deleted, deprecated, or changed
- Screenshots of new or changed UI, if applicable
- A summary of usage if this is a new feature or change to a public API (this should also be added to relevant documentation once released)
- Any alternative designs or approaches considered
- [PATCH  /api/v2/guardian/factors/push-notification/providers/sns](https://auth0.com/docs/api/management/v2/guardian/patch-sns)
- [PUT  /api/v2/guardian/factors/push-notification/providers/sns](https://auth0.com/docs/api/management/v2/guardian/put-sns)
- [GET  /api/v2/guardian/factors/push-notification/selected-provider](https://auth0.com/docs/api/managemen …

Adds support for managing SNS configuration - Push Notification - MFA policies

---

src/Auth0.ManagementApi/Models/Organization/OrganizationConnectionCreateRequest.cs

Allow Optional AssignMembershipOnLogin field to be nullable

---

src/Auth0.ManagementApi/Clients/BrandingClient.cs
src/Auth0.ManagementApi/Clients/IBrandingClient.cs
src/Auth0.ManagementApi/Models/Branding/BrandingPhoneNotificationTemplateCreateRequest.cs
src/Auth0.ManagementApi/Models/Branding/BrandingPhoneNotificationTemplateUpdateRequest.cs
src/Auth0.ManagementApi/Models/Branding/BrandingPhoneNotificationTemplates.cs
src/Auth0.ManagementApi/Models/Branding/BrandingPhoneNotificationTemplatesGetRequest.cs
src/Auth0.ManagementApi/Models/Branding/BrandingPhoneTestNotificationRequest.cs
src/Auth0.ManagementApi/Models/Branding/BrandingPhoneTestNotificationResponse.cs
tests/Auth0.ManagementApi.IntegrationTests/BrandingClientTests.cs

Added support for the following end-points
- [POST  /api/v2/branding/phone/providers/{id}/try](https://auth0.com/docs/api/management/v2/branding/try-phone-provider)
- [GET  /api/v2/branding/phone/templates](https://auth0.com/docs/api/management/v2/branding/get-phone-templates)
- [POST  /api/v2/branding/phone/templates](https://auth0.com/docs/api/management/v2/branding/create-phone-template)
- [GET  /api/v2/branding/phone/templates/{id}](https://auth0.com/docs/api/management/v2/branding/get-phone-template)
- [DELETE  /api/v2/branding/phone/templates/{id}](https://auth0.com/docs/api/management/v2/branding/delete-phone-template)
- [PATCH  /api/v2/branding/phone/templates/{id}](https://auth0.com/docs/api/management/v2/branding/update-phone-template)
- [PATCH …

Add support for managing Branding Phone Notification Templates

---

src/Auth0.ManagementApi/Clients/BrandingClient.cs
src/Auth0.ManagementApi/Clients/IBrandingClient.cs
src/Auth0.ManagementApi/Models/Branding/BrandingTheme.cs
src/Auth0.ManagementApi/Models/Branding/BrandingThemeBase.cs
tests/Auth0.ManagementApi.IntegrationTests/BrandingClientTests.cs

Added support for the following end-points:
- [POST  /api/v2/branding/themes](https://auth0.com/docs/api/management/v2/branding/post-branding-theme)
- [GET  /api/v2/branding/themes/default](https://auth0.com/docs/api/management/v2/branding/get-default-branding-theme)
- [GET  /api/v2/branding/themes/{themeId}](https://auth0.com/docs/api/management/v2/branding/get-branding-theme)
- [DELETE  /api/v2/branding/themes/{themeId}](https://auth0.com/docs/api/management/v2/branding/delete-branding-theme)
- [PATCH  /api/v2/branding/themes/{themeId}](https://auth0.com/docs/api/management/v2/branding/patch-branding-theme)
- Addresses the ask in #754 
- [SDK-5611](https://auth0team.atlassian.net/browse/SDK-5611)
Added the `Test_BrandingTheme_crud_sequence` test case that creates a new branding theme, …

Adding support for managing branding theme

---

src/Auth0.ManagementApi/Models/SelfServiceProfiles/EnabledOrganization.cs
src/Auth0.ManagementApi/Models/SelfServiceProfiles/SelfServiceSsoConnectionConfig.cs
tests/Auth0.ManagementApi.IntegrationTests/SelfServiceProfileTest.cs

- Built on the contribution from [kll2105](https://github.com/kll2105) in #772 
- Added missing fields in [Self Service SSO](https://auth0.com/docs/api/management/v2/self-service-profiles/post-sso-ticket)
- [Auth0 Docs](https://auth0.com/docs/api/management/v2/self-service-profiles/post-sso-ticket)
- [SDK-5713](https://auth0team.atlassian.net/browse/SDK-5713)
- #772 
[SDK-5713]: https://auth0team.atlassian.net/browse/SDK-5713?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add missing fields in SelfServiceSso config

---

Examples.md
src/Auth0.AuthenticationApi/AuthenticationApiClient.cs
src/Auth0.AuthenticationApi/ExtensionMethods.cs
src/Auth0.AuthenticationApi/IAuthenticationApiClient.cs
src/Auth0.AuthenticationApi/Models/Mfa/AssociateMfaAuthenticatorRequest.cs
src/Auth0.AuthenticationApi/Models/Mfa/AssociateMfaAuthenticatorResponse.cs
src/Auth0.AuthenticationApi/Models/Mfa/DeleteMfaAuthenticatorRequest.cs
src/Auth0.AuthenticationApi/Models/Mfa/MfaAuthenticator.cs
src/Auth0.AuthenticationApi/Models/Mfa/MfaChallengeRequest.cs
src/Auth0.AuthenticationApi/Models/Mfa/MfaChallengeResponse.cs
src/Auth0.AuthenticationApi/Models/Mfa/MfaOobTokenRequest.cs
src/Auth0.AuthenticationApi/Models/Mfa/MfaOobTokenResponse.cs
src/Auth0.AuthenticationApi/Models/Mfa/MfaOtpTokenRequest.cs
src/Auth0.AuthenticationApi/Models/Mfa/MfaOtpTokenResponse.cs
src/Auth0.AuthenticationApi/Models/Mfa/MfaRecoveryCodeRequest.cs
src/Auth0.AuthenticationApi/Models/Mfa/MfaRecoveryCodeResponse.cs
tests/Auth0.AuthenticationApi.IntegrationTests/ExtensionMethodsTests.cs
tests/Auth0.AuthenticationApi.IntegrationTests/MfaAuthenticationTests.cs

- Changes built on top of contributions from [czf](https://github.com/czf) in #698 #695 
- [/mfa/challenge](https://auth0.com/docs/api/authentication/muti-factor-authentication/request-mfa-challenge) 
- [/oauth/token - with otp](https://auth0.com/docs/api/authentication/muti-factor-authentication/verify-mfa-with-otp)
- [/oauth/token - with oob](https://auth0.com/docs/api/authentication/muti-factor-authentication/verify-with-out-of-band)
- [/oauth/token - with recovery code](https://auth0.com/docs/api/authentication/muti-factor-authentication/verify-with-recovery-code)
- [/mfa/associate](https://auth0.com/docs/api/authentication/muti-factor-authentication/add-an-authenticator)
- [/mfa/authenticators](https://auth0.com/docs/api/authentication/muti-factor-authentication/list-authenticators) …

Adds support to Enroll / Verify / List / Challenge / Delete Multi Factor Authenticators

---

.github/workflows/snyk.yml
Examples.md
src/Auth0.ManagementApi/Models/Client/ClientBase.cs
src/Auth0.ManagementApi/Models/Organization/OrganizationBase.cs
src/Auth0.ManagementApi/Models/Organization/OrganizationUpdateRequest.cs
src/Auth0.ManagementApi/Models/Tenant/DefaultTokenQuota.cs
src/Auth0.ManagementApi/Models/Tenant/Quota.cs
src/Auth0.ManagementApi/Models/Tenant/TenantSettingsBase.cs
src/Auth0.ManagementApi/Models/Tenant/TokenQuota.cs
tests/Auth0.AuthenticationApi.IntegrationTests/TokenTests.cs
tests/Auth0.ManagementApi.IntegrationTests/ClientGrantTests.cs
tests/Auth0.ManagementApi.IntegrationTests/ClientTests.cs
tests/Auth0.ManagementApi.IntegrationTests/JobsTest.cs
tests/Auth0.ManagementApi.IntegrationTests/OrganizationTests.cs
tests/Auth0.ManagementApi.IntegrationTests/SelfServiceProfileTest.cs
tests/Auth0.ManagementApi.IntegrationTests/TenantSettingsTests.cs
tests/Auth0.ManagementApi.IntegrationTests/TicketsTests.cs
tests/Auth0.ManagementApi.IntegrationTests/UsersTests.cs

- Adds support to update Default Token Quota at Tenant level
- Adds support to update Token Quota at Client level
- Adds support to update Token Quota at Organisation level
- [SDK-5882](https://auth0team.atlassian.net/browse/SDK-5882)
- Refer [examples](https://github.com/auth0/auth0.net/blob/master/Examples.md) for sample code.
[SDK-5882]: https://auth0team.atlassian.net/browse/SDK-5882?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Adds support to update Token Quota at different levels

---

src/Auth0.ManagementApi/Models/Tenant/TenantFlags.cs
src/Auth0.ManagementApi/Models/Tenant/TenantSettingsBase.cs
tests/Auth0.ManagementApi.IntegrationTests/TenantSettingsTests.cs

- Adds the following missing fields 
- `TenantSettings`
- `DefaultRedirectionUri`
- `AllowOrganizationNameInAuthenticationApi`
- `OidcLogout`
- `Sessions`
- `LegacySandboxVersion`
- `AuthorizationResponseIssParameterSupported`
- `TenantFlags`
- `DisableImpersonation`
- `AllowChangingEnableSso`
- `DashboardLogStreamsNext`
- `DashboardInsightsView`
- `DisableFieldsMapFix`
- `MfaShowFactorListOnEnrollment`
- `ImprovedSignupBotDetectionInClassic`
- `GenaiTrial`
- `CustomDomainsProvisioning`
- [SDK-5888](https://auth0team.atlassian.net/browse/SDK-5888)
- #803 
[SDK-5888]: https://auth0team.atlassian.net/browse/SDK-5888?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Adds missing fields in Tenant Settings and Tenant flags

---

src/Auth0.ManagementApi/Clients/IUsersClient.cs
src/Auth0.ManagementApi/Clients/UsersClient.cs

- Added support for Deleting all Authenticators registered to a user.
- [SDK-5706](https://auth0team.atlassian.net/browse/SDK-5706)
- #790 
- [Auth0 Docs](https://auth0.com/docs/api/management/v2/users/delete-authenticators) 
[SDK-5706]: https://auth0team.atlassian.net/browse/SDK-5706?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add support for Delete authenticators registered to a user

---

playground/Auth0.NET6/Auth0.NET6.csproj
playground/Auth0.NETCore3/Auth0.NETCore3.csproj
playground/Auth0.NETFramework/Auth0.NETFramework.csproj
src/Auth0.AuthenticationApi/Auth0.AuthenticationApi.csproj
src/Auth0.Core/Auth0.Core.csproj
src/Auth0.Core/Exceptions/ApiError.cs
src/Auth0.Core/Exceptions/ApiException.cs
src/Auth0.Core/Exceptions/ErrorApiException.cs
src/Auth0.Core/Exceptions/QuotaLimit.cs
src/Auth0.Core/Exceptions/RateLimit.cs
src/Auth0.Core/Exceptions/RateLimitApiException.cs
src/Auth0.Core/Extensions.cs
src/Auth0.Core/Serialization/ApiErrorConverter.cs
src/Auth0.Core/Serialization/StringOrObjectAsStringConverter.cs
src/Auth0.Core/Serialization/StringOrStringArrayJsonConverter.cs
src/Auth0.Core/Utils.cs
src/Auth0.ManagementApi/Auth0.ManagementApi.csproj
src/Directory.Build.props
tests/Auth0.AuthenticationApi.IntegrationTests/Auth0.AuthenticationApi.IntegrationTests.csproj
tests/Auth0.Core.UnitTests/Auth0.Core.UnitTests.csproj
tests/Auth0.IntegrationTests.Shared/Auth0.IntegrationTests.Shared.csproj
tests/Auth0.ManagementApi.IntegrationTests/Auth0.ManagementApi.IntegrationTests.csproj

- Add dependency on `Polysharp` library `v1.15.0`
- Use latest language features in all projects
- Use Null Reference Types in `Auth0.Core` Project
- [SDK-5405](https://auth0team.atlassian.net/browse/SDK-5405)
- #750 
All unit tests and integration tests are passing.
[SDK-5405]: https://auth0team.atlassian.net/browse/SDK-5405?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Use Polysharp to take advantage of latest language features

---

src/Auth0.ManagementApi/Models/Branding/BrandingPhoneTestNotificationResponse.cs
src/Auth0.ManagementApi/Models/Branding/BrandingThemeBase.cs

- Changed the data-types of the following from `int` to `float` to match the documentation
- `BrandingPhoneTestNotificationResponse.Code`
- `BrandingThemeBorder.ButtonBorderRadius`
- `BrandingThemeBorder.ButtonBorderWeight`
- `BrandingThemeBorder.InputBorderRadius`
- `BrandingThemeBorder.InputBorderWeight`
- `BrandingThemeBorder.WidgetBorderWeight`
- `BrandingThemeBorder.WidgetCornerRadius`
- `BrandingThemeFonts.ReferenceTextSize`
- `BrandingThemeFonts.LogoHeight`
- `BrandingThemeFontsBase.Size`
- Fixes #823 
- [SDK-6165](https://auth0team.atlassian.net/browse/SDK-6165)
[SDK-6165]: https://auth0team.atlassian.net/browse/SDK-6165?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: data-type from `int` to `float` for Branding related configs

---

src/Auth0.AuthenticationApi/AuthenticationApiClient.cs
src/Auth0.AuthenticationApi/IAuthenticationApiClient.cs

- Deprecates `IAuthenticationApiClient.GetImpersonationUrlAsync`
- [SDK-6230](https://auth0team.atlassian.net/browse/SDK-6230)
N/A
[SDK-6230]: https://auth0team.atlassian.net/browse/SDK-6230?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: Deprecate GetImpersonationUrlAsync

---

src/Auth0.ManagementApi/Clients/IUsersClient.cs
src/Auth0.ManagementApi/Clients/UsersClient.cs

- Adds optional `CancellationToken` parameter to `IUsersClient.DeleteAsync`.
- Refactor to remove redundant method documentations and use `<inheritdoc />` instead.
- Fixes #861 
- [SDK-6665](https://auth0team.atlassian.net/browse/SDK-6665)
[SDK-6665]: https://auth0team.atlassian.net/browse/SDK-6665?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Adds CancellationToken parameter in IUsersClient.DeleteAsync

---

src/Auth0.Core/Utils.cs
src/Auth0.ManagementApi/Clients/BaseClient.cs
src/Auth0.ManagementApi/Clients/ClientsClient.cs
src/Auth0.ManagementApi/Clients/IClientsClient.cs
src/Auth0.ManagementApi/Models/Client/EnabledConnectionsForClientGetRequest.cs
tests/Auth0.ManagementApi.IntegrationTests/ClientTests.cs

- Adds support to query enabled clients for a specific client using `IClientsClient.GetEnabledConnectionsForClientAsync`. 
- Built on top of #849 (PR by [mikejr83](https://github.com/mikejr83) )
- REST Management API Documentation [Get enabled connections for a client](https://auth0.com/docs/api/management/v2/clients/get-client-connections)
- #848 , #849 
- [SDK-6664](https://auth0team.atlassian.net/browse/SDK-6664)
[SDK-6664]: https://auth0team.atlassian.net/browse/SDK-6664?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Adds support for getting connections enabled for a specific client
