auth0/auth0.net

Auth0.Net/Client.cs
=> Support password resets for a DB connection

Auth0.Net.sln, src/Auth0.AuthenticationApi.Client/Auth0.AuthenticationApi.Client.csproj, src/Auth0.AuthenticationApi.Client/AuthenticationApiClient.cs, src/Auth0.AuthenticationApi.Client/IAuthenticationApiClient.cs, src/Auth0.AuthenticationApi.Client/Properties/AssemblyInfo.cs
Add the base, empty Auth API project, so @advancedrei and myself have the same base to work from.
@ntotten If you can fit this in quickly somewhere between your Thanksgiving celebrations it will be appreciated ;)
=> Add Auth API

nuget/Auth0.AuthenticationApi.nuspec, nuget/Auth0.Core.nuspec, nuget/Auth0.ManagementApi.nuspec, nuget/Auth0.nuspec, src/Auth0.AuthenticationApi/Auth0.AuthenticationApi.csproj, src/Auth0.AuthenticationApi/AuthenticationApiClient.cs, src/Auth0.AuthenticationApi/Builders/AuthorizationUrlBuilder.cs, src/Auth0.AuthenticationApi/IAuthenticationApiClient.cs, src/Auth0.AuthenticationApi/Models/ImpersonationRequest.cs, src/Auth0.AuthenticationApi/Models/UnlinkUserRequest.cs, tests/Auth0.AuthenticationApi.IntegrationTests/Auth0.AuthenticationApi.IntegrationTests.csproj, tests/Auth0.AuthenticationApi.IntegrationTests/ImpersonationTests.cs
- Completed outstanding methods on Auth API
- Created Nuget packages for V2.0.0 and released to Nuget
=> Outstanding auth api work

docs/index.md
Closes #85 
This seems to be an issue with docfx. More investigation is needed when there is time.
=> Remove problematic links from homepage.

docs/index.md
Add a description on thread safety for both clients.
=> Description on thread safety

src/Auth0.ManagementApi/Models/ClientBase.cs, src/Auth0.ManagementApi/Models/ClientResourceServerAssociation.cs, tests/ConsoleWorkbench/Program.cs
Add ClientResourceServerAssociation class for associating resource servers with clients
This is fix for #147
=> Add ClientResourceServerAssociation class

src/Auth0.ManagementApi/Models/UserCreateRequest.cs
Adds missing property `UserId` to the `CreateUserRequest` model
=> CreateUserRequest UserId

src/Auth0.ManagementApi/Models/EmailVerificationTicketRequest.cs, src/Auth0.ManagementApi/Models/PasswordChangeTicketRequest.cs
=> Add ttl_sec property in email verification and password reset ticket request

src/Auth0.ManagementApi/Models/ClientBase.cs
Fixing problems while create or update client settings in a tenant
=> added missing fields to ClientBase class

src/Auth0.Core/Http/Utils.cs
See https://stackoverflow.com/questions/4396598/whats-the-difference-between-escapeuristring-and-escapedatastring for explanation of why this should be used instead
=> Use EscapeDatastring instead of EscapeUriString. Closes #194

src/Auth0.ManagementApi/Models/Identity.cs
=> Add AccessTokenSecret for Twitter identities

docs/api/Auth0.ManagementApi.Models.ClientApplicationType.html
Updating to match changed Dashboard text
=> Match Dashboard

README.md
1. Changed 'mantained' to 'maintained'.
2. Changed 'accomodate' to 'accommodate'.
=> Fixed 2 Typos

README.md
Changed description of links to more meaningful descriptions.
=> Use link descriptions like other links in the readme

tests/Auth0.ManagementApi.IntegrationTests/EmailTemplatesTests.cs
=> Minor change to remove unused variable

build.sh
Hello.
I modified the UUOC(useless use of cat)
what do you think?
Thanks.
=> Fix useless use of cat

build/common.props
Update version number and release notes for v5.11.0
=> Release v5.11.0

build.cake, build/common.props
Remove last traces of AppVeyor and use Azure CI's build numbers to suffix the build numbers.
=> Remove AppVeyor CI stuff, enable Azure CI build numbers

src/Auth0.AuthenticationApi/AuthenticationApiClient.cs, src/Auth0.Core/Http/ApiConnection.cs, src/Auth0.ManagementApi/Clients/BlacklistedTokensClient.cs, src/Auth0.ManagementApi/Clients/ClientBase.cs, src/Auth0.ManagementApi/Clients/ClientGrantsClient.cs, src/Auth0.ManagementApi/Clients/ClientsClient.cs, src/Auth0.ManagementApi/Clients/ConnectionsClient.cs, src/Auth0.ManagementApi/Clients/CustomDomainsClient.cs, src/Auth0.ManagementApi/Clients/DeviceCredentialsClient.cs, src/Auth0.ManagementApi/Clients/EmailProviderClient.cs, src/Auth0.ManagementApi/Clients/EmailTemplatesClient.cs, src/Auth0.ManagementApi/Clients/GuardianClient.cs, src/Auth0.ManagementApi/Clients/JobsClient.cs, src/Auth0.ManagementApi/Clients/ResourceServersClient.cs, src/Auth0.ManagementApi/Clients/RolesClient.cs, src/Auth0.ManagementApi/Clients/RulesClient.cs, src/Auth0.ManagementApi/Clients/TenantSettingsClient.cs, src/Auth0.ManagementApi/Clients/TicketsClient.cs, src/Auth0.ManagementApi/Clients/UserBlocksClient.cs, src/Auth0.ManagementApi/Clients/UsersClient.cs, src/Auth0.ManagementApi/ManagementApiClient.cs
- Replaced invalid <inheritdoc/> with actual docs
- Fixed missing/incompete return tasks (especially common when returned just Task)
- Added .'s to end of params etc.
- Various other small improvements
=> Clean up xmldoc for clients

tests/Auth0.ManagementApi.IntegrationTests/EmailProviderTests.cs, tests/Auth0.ManagementApi.IntegrationTests/TenantSettingsTests.cs
A few integration tests that were previously disabled/skipped now work again.
=> Fix some integration tests

src/Auth0.ManagementApi/Models/User.cs, src/Auth0.ManagementApi/Models/UserBase.cs, src/Auth0.ManagementApi/Models/UserCreateRequest.cs, src/Auth0.ManagementApi/Models/UserUpdateRequest.cs
=> Move some user properties to shared base class

src/Auth0.ManagementApi/Models/ClientUpdateRequest.cs, src/Auth0.ManagementApi/Models/TenantChangePassword.cs, src/Auth0.ManagementApi/Models/TenantDeviceFlow.cs, src/Auth0.ManagementApi/Models/TenantDeviceFlowCharset.cs, src/Auth0.ManagementApi/Models/TenantErrorPage.cs, src/Auth0.ManagementApi/Models/TenantFlags.cs, src/Auth0.ManagementApi/Models/TenantGuardianMfa.cs, src/Auth0.ManagementApi/Models/TenantGuardianMfaPage.cs, src/Auth0.ManagementApi/Models/TenantSettingsBase.cs, tests/Auth0.ManagementApi.IntegrationTests/TenantSettingsTests.cs
Adds various settings to the Tenant APIs that were missing from the .NET SDK.
=> Add missing Tenant settings

.snyk
Add a snyk policy file to ignore vulnerability reports that don't affect this SDK
=> Add snyk policy file

build/common.props
Update release number and release notes for 6.4.0 release.
=> Prepare 6.4.0 release

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md
This updates the templates to make sure that check boxes are shown in the checklists.
=> Update templates to make sure check boxes are shown.

src/Auth0.AuthenticationApi/AuthenticationApiClient.cs, src/Auth0.AuthenticationApi/Exceptions/IdentityTokenValidationException.cs, src/Auth0.AuthenticationApi/IdentityTokenValidator.cs, src/Auth0.Core/Http/ApiConnection.cs, src/Auth0.ManagementApi/ManagementApiClient.cs
Address a few compiler warnings and VS informational tips.
=> Miscellaneous cleanup

src/Auth0.AuthenticationApi/Models/SignupUserRequest.cs, src/Auth0.AuthenticationApi/Models/SignupUserResponse.cs, src/Auth0.AuthenticationApi/Models/UserMaintenanceRequestBase.cs, tests/Auth0.AuthenticationApi.IntegrationTests/DatabaseConnectionTests.cs
Added root profile attributes to the signup request and response.
=> Root profile fields on signup

src/Auth0.AuthenticationApi/AuthenticationApiClient.cs, src/Auth0.AuthenticationApi/HttpClientAuthenticationConnection.cs, src/Auth0.AuthenticationApi/IAuthenticationConnection.cs
Replaces the IApiConnection with IAuthenticationConnection and ApiConnection with HttpClientAuthenticationConnection in order to:
1. Improve testability
2. Separate Auth and Management functionality
3. Clean up documentation
=> Replaces IApiConnection with IAuthenticationConnection

src/Auth0.ManagementApi/Models/EnrollmentAuthMethod.cs, src/Auth0.ManagementApi/Models/EnrollmentsResponse.cs
=> Fix EnrollmentAuthMethod enum Authenticator

src/Auth0.ManagementApi/Clients/ClientGrantsClient.cs, src/Auth0.ManagementApi/Clients/DeviceCredentialsClient.cs, src/Auth0.ManagementApi/Clients/RolesClient.cs, src/Auth0.ManagementApi/Clients/RulesClient.cs, src/Auth0.ManagementApi/Clients/UsersClient.cs, src/Auth0.ManagementApi/ManagementApiClient.cs
Management API was using a mix of interfaces and the concrete type for the connection. 
Normalizes on the interface.
=> Switch management connection to interface from concrete type

src/Auth0.AuthenticationApi/HttpClientAuthenticationConnection.cs
=> Remove netstandard1_4 conditional from auth

src/Auth0.AuthenticationApi/AuthenticationApiClient.cs, src/Auth0.AuthenticationApi/HttpClientAuthenticationConnection.cs, src/Auth0.AuthenticationApi/Tokens/IdTokenValidationException.cs, src/Auth0.Core/ApiError.cs, src/Auth0.Core/Exceptions/ApiException.cs, src/Auth0.Core/Exceptions/ErrorApiException.cs, src/Auth0.Core/Exceptions/RateLimitApiException.cs, tests/Auth0.AuthenticationApi.IntegrationTests/AccessTokenTests.cs, tests/Auth0.AuthenticationApi.IntegrationTests/AuthenticationTests.cs, tests/Auth0.AuthenticationApi.IntegrationTests/Builders/UriBuildersTests.cs, tests/Auth0.AuthenticationApi.IntegrationTests/DatabaseConnectionTests.cs, tests/Auth0.AuthenticationApi.IntegrationTests/ImpersonationTests.cs, tests/Auth0.AuthenticationApi.IntegrationTests/MetadataTests.cs, tests/Auth0.AuthenticationApi.IntegrationTests/PasswordlessTests.cs, tests/Auth0.AuthenticationApi.IntegrationTests/TokenTests.cs, tests/Auth0.AuthenticationApi.IntegrationTests/UserInfoDeserializationTests.cs, tests/Auth0.ManagementApi.IntegrationTests/ClientTests.cs, tests/Auth0.ManagementApi.IntegrationTests/TestBase.cs
Just addressing a bunch of style analysis things like checking against parameters etc.  Individual commits broken down by type.
=> Address analysis warnings in AuthenticationApi

tests/Auth0.AuthenticationApi.IntegrationTests/Tokens/IdTokenValidatorIntegrationTests.cs, tests/Auth0.ManagementApi.IntegrationTests/ClientGrantTests.cs, tests/Auth0.ManagementApi.IntegrationTests/ClientTests.cs, tests/Auth0.ManagementApi.IntegrationTests/ConnectionTests.cs, tests/Auth0.ManagementApi.IntegrationTests/CustomDomainsTests.cs, tests/Auth0.ManagementApi.IntegrationTests/DeviceCredentialsTests.cs, tests/Auth0.ManagementApi.IntegrationTests/EmailTemplatesTests.cs, tests/Auth0.ManagementApi.IntegrationTests/GuardianTests.cs, tests/Auth0.ManagementApi.IntegrationTests/JobsTest.cs, tests/Auth0.ManagementApi.IntegrationTests/LoadTests.cs, tests/Auth0.ManagementApi.IntegrationTests/LogsTests.cs, tests/Auth0.ManagementApi.IntegrationTests/ManagementApiClientTests.cs, tests/Auth0.ManagementApi.IntegrationTests/ResourceServerTests.cs, tests/Auth0.ManagementApi.IntegrationTests/RolesTests.cs, tests/Auth0.ManagementApi.IntegrationTests/RulesTests.cs, tests/Auth0.ManagementApi.IntegrationTests/StatsTests.cs, tests/Auth0.ManagementApi.IntegrationTests/TenantSettingsTests.cs, tests/Auth0.ManagementApi.IntegrationTests/TestBase.cs, tests/Auth0.ManagementApi.IntegrationTests/TicketsTests.cs, tests/Auth0.ManagementApi.IntegrationTests/UserBlockTests.cs, tests/Auth0.ManagementApi.IntegrationTests/UsersTests.cs
A bunch of clean-up on the integration test code.  No product changes.
=> Integration test improvements

tests/Auth0.AuthenticationApi.IntegrationTests/Tokens/IdTokenValidatorIntegrationTests.cs
Adds integration test coverage for the HS256 ID token signature verification.
=> Add HS256 token signing integration test

build/common.props
7.0.0 has so many breaking changes and it's so close to the holiday period it makes sense to put this in a beta for now.
=> Prepare 7.0.0 beta 1

README.md, docs-source/index.md, docs-source/migrating-to-v7.md, docs-source/migrating.md
Provides the migration guide for v7 as well as some minor doc improvements and tweaks for v7.
=> Migration guide for v7 and doc tweaks

LICENSE, build/common.props
Updates the release notes, version number and copyright notice for the 7.0.0 release.
=> Update changelog and version number for 7.0.0

build/common.props, src/Auth0.ManagementApi/Models/Connection.cs, src/Auth0.ManagementApi/Models/ConnectionBase.cs, src/Auth0.ManagementApi/Models/ConnectionCreateRequest.cs, src/Auth0.ManagementApi/Models/ConnectionUpdateRequest.cs, tests/Auth0.ManagementApi.IntegrationTests/ConnectionTests.cs, tests/Auth0.ManagementApi.IntegrationTests/ManagementApiClientTests.cs
Fixes #361 
Additionally cleans up some old test header code.
=> Add missing domain connection properties

src/Auth0.AuthenticationApi/HttpClientAuthenticationConnection.cs
As per #367 but for HttpClientAuthenticationConnection
=> Fix dispose problem on HttpClientAuthenticationConnection.GetAsync

src/Auth0.Core/Exceptions/ApiError.cs, src/Auth0.Core/Serialization/ApiErrorConverter.cs, tests/Auth0.Core.UnitTests/ApiErrorDeserializationTests.cs
=> Capture extra error properties e.g. mfa_required

src/Auth0.ManagementApi/Clients/JobsClient.cs, src/Auth0.ManagementApi/HttpClientManagementConnection.cs, src/Auth0.ManagementApi/Models/Job.cs, src/Auth0.ManagementApi/Models/JobSummary.cs, src/Auth0.ManagementApi/Models/VerifyEmailJobRequest.cs, tests/Auth0.ManagementApi.IntegrationTests/Auth0.ManagementApi.IntegrationTests.csproj, tests/Auth0.ManagementApi.IntegrationTests/JobsTest.cs
- Fixes user import job.
- Re-enabled jobs integration tests disabled in 2017.
- Improves test coverage a little.
- Adds `send_verification_email` parameter to import users.
- Fleshes out Job class with additional possible return properties.
=> Fix import user  job

src/Auth0.AuthenticationApi/HttpClientAuthenticationConnection.cs, src/Auth0.ManagementApi/HttpClientManagementConnection.cs
=> Force JSON.NET DateParse handling

src/Auth0.ManagementApi/Models/UserBlock.cs
Fixes https://github.com/auth0/auth0.net/issues/405
=> Adding the "connection" property

src/Auth0.ManagementApi/HttpClientManagementConnection.cs
=> Fix multipart boolean form casing

src/Auth0.ManagementApi/Clients/JobsClient.cs, src/Auth0.ManagementApi/Models/UsersExportsJobField.cs, src/Auth0.ManagementApi/Models/UsersExportsJobFormat.cs, src/Auth0.ManagementApi/Models/UsersExportsJobRequest.cs, tests/Auth0.ManagementApi.IntegrationTests/JobsTest.cs
=> [SDK-1512] Implement the POST Job Users Export endpoint

src/Auth0.AuthenticationApi/Models/AuthorizationCodeRequestBase.cs
=> Fix typo with AuthorizationCodeRequestBase

CHANGELOG.md, build/common.props
**Added**
- Allow creating and updating RefreshToken settings for Clients [\#451](https://github.com/auth0/auth0.net/pull/451) ([SamTheWizard](https://github.com/SamTheWizard))
=> Prepare 7.3.2

src/Auth0.ManagementApi/Clients/DeviceCredentialsClient.cs, src/Auth0.ManagementApi/Models/GetDeviceCredentialsRequest.cs, tests/Auth0.ManagementApi.IntegrationTests/Auth0.ManagementApi.IntegrationTests.csproj, tests/Auth0.ManagementApi.IntegrationTests/DeviceCredentialsTests.cs
=> Add pagination to retrieving Device Credentials

src/Auth0.ManagementApi/Models/PasswordChangeTicketRequest.cs
=> Add ClientId to PasswordChangeTicketRequest

CHANGELOG.md, build/common.props, docs/api/Auth0.ManagementApi.Clients.BaseClient.html, docs/api/Auth0.ManagementApi.Clients.BrandingClient.html, docs/api/Auth0.ManagementApi.Clients.HooksClient.html, docs/api/Auth0.ManagementApi.Clients.html, docs/api/Auth0.ManagementApi.ManagementApiClient.html, docs/api/Auth0.ManagementApi.Models.Branding.html, docs/api/Auth0.ManagementApi.Models.BrandingBase.html, docs/api/Auth0.ManagementApi.Models.BrandingColors.html, docs/api/Auth0.ManagementApi.Models.BrandingFont.html, docs/api/Auth0.ManagementApi.Models.BrandingUpdateRequest.html, docs/api/Auth0.ManagementApi.Models.GetHooksRequest.html, docs/api/Auth0.ManagementApi.Models.Hook.html, docs/api/Auth0.ManagementApi.Models.HookBase.html, docs/api/Auth0.ManagementApi.Models.HookCreateRequest.html, docs/api/Auth0.ManagementApi.Models.HookUpdateRequest.html, docs/api/Auth0.ManagementApi.Models.UniversalLoginTemplate.html, docs/api/Auth0.ManagementApi.Models.UniversalLoginTemplateUpdateRequest.html, docs/api/Auth0.ManagementApi.Models.html, docs/api/toc.html, docs/manifest.json, docs/xrefmap.yml
Prepare everything for the 7.6.0 release
=> Release 7.6.0

src/Auth0.AuthenticationApi/Tokens/IdTokenRequirements.cs
Release 7.7.0 was missing an XML comment
=> Add organization to XML Docs

docs/api/Auth0.ManagementApi.Clients.OrganizationsClient.html, docs/api/Auth0.ManagementApi.Models.OrganizationGetAllInvitationsRequest.html, docs/api/Auth0.ManagementApi.Models.OrganizationGetInvitationRequest.html, docs/api/Auth0.ManagementApi.Models.html, docs/api/toc.html, docs/manifest.json, docs/xrefmap.yml, src/Auth0.ManagementApi/Clients/OrganizationsClient.cs, src/Auth0.ManagementApi/Models/OrganizationGetAllRequest.cs, src/Auth0.ManagementApi/Models/OrganizationGetInvitationRequest.cs, tests/Auth0.ManagementApi.IntegrationTests/OrganizationTests.cs
There were a few mistakes in the type names and the XML documentation that need to be fixed before releasing.
=> Fix organization docs

README.md
Reverts commit that accidentally got merged from https://github.com/auth0/auth0.net/pull/493
=> Revert "Test CI (#493)"

README.md, src/Auth0.ManagementApi/Models/UserCreateRequest.cs
Closes #496 
Updated the password property XML documentation summary to include email as a non mandatory connection type.
=> Update UserCreateRequest password property xml documentation

src/Auth0.ManagementApi/HttpClientManagementConnection.cs, tests/Auth0.ManagementApi.IntegrationTests/EmailProviderTests.cs, tests/Auth0.ManagementApi.IntegrationTests/EmailTemplatesTests.cs
Increase the max timeout when hitting rate limits. Also disabled two tests that are giving an HTTP 500.
=> Increase delay between subsequent retries

src/Auth0.ManagementApi/Models/EnrollmentAuthMethod.cs, src/Auth0.ManagementApi/Models/EnrollmentsResponse.cs
Add missing enum values for EnrollmentAuthMethods to avoid runtime serialization errors.
=> add webauthn-* enrollment auth methods

src/Auth0.Core/Utils.cs, src/Auth0.ManagementApi/Clients/GuardianClient.cs
Ensures all Guardian Factors can be updated instead of only two.
#534
=> Support updating all guardian factors

CHANGELOG.md, build/common.props, docs/api/Auth0.ManagementApi.Clients.RulesConfigClient.html, docs/api/Auth0.ManagementApi.HttpClientManagementConnection.html, docs/api/Auth0.ManagementApi.Models.Connection.html, docs/manifest.json, docs/xrefmap.yml
**Changed**
- Add ProvisioningTicketUrl [\#562](https://github.com/auth0/auth0.net/pull/562) ([zzanol](https://github.com/zzanol))
**Security**
- [Snyk] Security upgrade Newtonsoft.Json from 12.0.3 to 13.0.1 [\#560](https://github.com/auth0/auth0.net/pull/560) ([crew-security](https://github.com/crew-security))
- [Snyk] Security upgrade Microsoft.IdentityModel.Protocols.OpenIdConnect from 5.6.0 to 6.5.0 [\#559](https://github.com/auth0/auth0.net/pull/559) ([snyk-bot](https://github.com/snyk-bot))
=> Release 7.16.0

src/Auth0.ManagementApi/IManagementApiClient.cs, src/Auth0.ManagementApi/ManagementApiClient.cs
Moving IDisposable on to IManagementApiClient
##580
=> #580: Moving IDisposable on to IManagementApiClient

CHANGELOG.md, build/common.props, docs/api/Auth0.ManagementApi.IManagementApiClient.html, docs/api/Auth0.ManagementApi.ManagementApiClient.html, docs/manifest.json
**Fixed**
- Moving IDisposable on to IManagementApiClient [\#581](https://github.com/auth0/auth0.net/pull/581) ([kevbite](https://github.com/kevbite))
=> Release 7.17.1

CHANGELOG.md, build/common.props, docs/api/Auth0.ManagementApi.Models.OrganizationCreateRequest.html, docs/manifest.json, docs/xrefmap.yml
**Changed**
- Support EnabledConnections in OrganizationCreateRequest [\#585](https://github.com/auth0/auth0.net/pull/585) ([ssurowiec](https://github.com/ssurowiec))
=> Release 7.17.2

CHANGELOG.md, build/common.props, docs/api/Auth0.ManagementApi.Clients.ActionsClient.html, docs/api/Auth0.ManagementApi.Clients.IActionsClient.html, docs/api/Auth0.ManagementApi.Models.AttackProtection.BreachedPasswordDetection.html, docs/api/Auth0.ManagementApi.Models.AttackProtection.BreachedPasswordDetectionStage.StageEntry.html, docs/api/Auth0.ManagementApi.Models.AttackProtection.BreachedPasswordDetectionStage.html, docs/api/toc.html, docs/manifest.json, docs/xrefmap.yml, package-lock.json, package.json
**Changed**
- [SDK-3641] Support stage property in Breached Password Detection configuration [\#591](https://github.com/auth0/auth0.net/pull/591) ([ewanharris](https://github.com/ewanharris))
[SDK-3641]: https://auth0team.atlassian.net/browse/SDK-3641?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Release 7.17.3

CHANGELOG.md, build/common.props, docs/api/Auth0.AuthenticationApi.IAuthenticationApiClient.html, docs/manifest.json, package-lock.json, package.json
**Changed**
- Move IDisposable to IAuthenticationApiClient [\#611](https://github.com/auth0/auth0.net/pull/611) ([frederikprijck](https://github.com/frederikprijck))
=> Release 7.19.1

CHANGELOG.md, build/common.props, docs/api/Auth0.AuthenticationApi.AuthenticationApiClient.html, docs/api/Auth0.AuthenticationApi.IAuthenticationApiClient.html, docs/api/Auth0.AuthenticationApi.Models.RevokeRefreshTokenRequest.html, docs/api/Auth0.AuthenticationApi.Models.html, docs/api/toc.html, docs/manifest.json, docs/xrefmap.yml, package-lock.json, package.json
**Added**
- Added revoke refresh token endpoint support [\#617](https://github.com/auth0/auth0.net/pull/617) ([msmolka](https://github.com/msmolka))
=> Release 7.20.0

CHANGELOG.md, build/common.props, docs/api/Auth0.ManagementApi.Clients.ClientsClient.html, docs/api/Auth0.ManagementApi.Clients.DeviceCredentialsClient.html, docs/api/Auth0.ManagementApi.Clients.IClientsClient.html, docs/api/Auth0.ManagementApi.Clients.IDeviceCredentialsClient.html, docs/api/Auth0.ManagementApi.Models.Client.html, docs/api/Auth0.ManagementApi.Models.ClientAuthenticationMethods.html, docs/api/Auth0.ManagementApi.Models.ClientCreateRequest.html, docs/api/Auth0.ManagementApi.Models.ClientCredentialCreateRequest.html, docs/api/Auth0.ManagementApi.Models.ClientCredentialUpdateRequest.html, docs/api/Auth0.ManagementApi.Models.ClientUpdateRequest.html, docs/api/Auth0.ManagementApi.Models.CreateClientAuthenticationMethods.html, docs/api/Auth0.ManagementApi.Models.CreatePrivateKeyJwt.html, docs/api/Auth0.ManagementApi.Models.Credential.html, docs/api/Auth0.ManagementApi.Models.CredentialId.html, docs/api/Auth0.ManagementApi.Models.PrivateKeyJwt.html, docs/api/Auth0.ManagementApi.Models.html, docs/api/toc.html, docs/manifest.json, docs/xrefmap.yml, package-lock.json, package.json
**Added**
- Add support for Client Credentials endpoint support in Management API [\#607](https://github.com/auth0/auth0.net/pull/607) ([frederikprijck](https://github.com/frederikprijck))
- Added cancellation token to device credentials request [\#619](https://github.com/auth0/auth0.net/pull/619) ([msmolka](https://github.com/msmolka))
=> Release 7.21.0

CHANGELOG.md, build/common.props, docs/api/Auth0.ManagementApi.Clients.ClientsClient.html, docs/api/Auth0.ManagementApi.Clients.IClientsClient.html, docs/api/Auth0.ManagementApi.Models.EmailVerificationTicketRequest.html, docs/manifest.json, docs/xrefmap.yml, package-lock.json, package.json
**Fixed**
- Add ClientId to EmailVerificationTicket [\#629](https://github.com/auth0/auth0.net/pull/629) ([bellascalzi1](https://github.com/bellascalzi1))
=> Release 7.21.1

src/Auth0.ManagementApi/Models/OrganizationUpdateRequest.cs
Add the Organization name to the Organization update model so that the name can be updated via the SDK. 
https://github.com/auth0/auth0.net/issues/638
=> Add Name to Org Update Request

src/Auth0.ManagementApi/Models/OrganizationRequireBehavior.cs
Add missing enum value for OrganizationRequireBehavior
Closes #636
=> Add post_login_prompt to OrganizationRequireBehavior

.github/workflows/publish.yml
Publishes to Nuget from Github Actions.
=> Add Nuget publish to Github Actions

CHANGELOG.md, build/common.props, docs/api/Auth0.ManagementApi.Models.User.html, docs/api/Auth0.ManagementApi.Models.UserBase.html, docs/api/Auth0.ManagementApi.Models.UserCreateRequest.html, docs/api/Auth0.ManagementApi.Models.UserUpdateRequest.html, docs/manifest.json, docs/xrefmap.yml, package-lock.json, package.json
**Changed**
- added generic get/set metadata methods on UserBase [\#646](https://github.com/auth0/auth0.net/pull/646) ([MichaelPruefer](https://github.com/MichaelPruefer))
=> Release 7.22.3

src/Auth0.ManagementApi/Models/Connection.cs, src/Auth0.ManagementApi/Models/ConnectionBase.cs
Move IsDomainConnection into ConnectionBase so that it's available on ConnectionUpdateRequest
https://auth0.com/docs/api/management/v2/connections/patch-connections-by-id
=> Move IsDomainConnection down into ConnectionBase

src/Auth0.ManagementApi/Clients/IOrganizationsClient.cs, src/Auth0.ManagementApi/Clients/OrganizationsClient.cs, src/Auth0.ManagementApi/Models/OrganizationGetAllMembersRequest.cs, tests/Auth0.ManagementApi.IntegrationTests/OrganizationTests.cs
Adds fields and include_fields to Organizations.GetAllMembersAsync
Closes #659 
=> Add fields to Organizations Get All Members

src/Auth0.ManagementApi/IManagementApiClient.cs
- Add IGrantsClient interface property to IManagementApiClinet
=> Add Grants to IManagementApiClient

tests/Auth0.ManagementApi.IntegrationTests/ClientTests.cs
=> Add tests for oidc logout

tests/Auth0.ManagementApi.IntegrationTests/OrganizationTests.cs
Some of the organization tests are flakey, disabling one for now.
=> Skipping a flakey test for now

tests/Auth0.ManagementApi.IntegrationTests/UserBlockTests.cs
Disables a test that appears to be broken, shouldn't be an issue on our end but it's blocking us.
=> Disable broken test

src/Auth0.ManagementApi/Models/LogStreamType.cs
Adds the missing LogStream types as per https://auth0.com/docs/api/management/v2/log-streams/get-log-streams#response-messages
https://auth0.com/docs/api/management/v2/log-streams/get-log-streams#response-messages
=> Update LogStreamType to include all types

tests/Auth0.AuthenticationApi.IntegrationTests/TokenTests.cs
Temporarily ignoring a test case which is failing due to issues in tenant configuration.
The test case works fine when pointed to another tenant that has proper configuration.
=> Ignore test failing due to tenant configuration issues

src/Auth0.ManagementApi/Models/Actions/Action.cs, src/Auth0.ManagementApi/Models/Actions/ActionDependency.cs, src/Auth0.ManagementApi/Models/Actions/ActionOption.cs, src/Auth0.ManagementApi/Models/Actions/ActionRequiredBase.cs, src/Auth0.ManagementApi/Models/Actions/ActionSemVer.cs, src/Auth0.ManagementApi/Models/Actions/ActionSupportedTrigger.cs, src/Auth0.ManagementApi/Models/Actions/ActionsRequiredConfiguration.cs, src/Auth0.ManagementApi/Models/Actions/ActionsRequiredSecrets.cs, src/Auth0.ManagementApi/Models/Actions/BindingPolicy.cs, src/Auth0.ManagementApi/Models/Actions/CompatibleTrigger.cs, src/Auth0.ManagementApi/Models/Actions/CurrentRelease.cs, src/Auth0.ManagementApi/Models/Actions/FeatureType.cs, src/Auth0.ManagementApi/Models/Actions/Integration.cs, src/Auth0.ManagementApi/Models/Actions/Trigger.cs, tests/Auth0.ManagementApi.IntegrationTests/ActionsTests.cs, tests/Auth0.ManagementApi.IntegrationTests/Auth0.ManagementApi.IntegrationTests.csproj, tests/Auth0.ManagementApi.IntegrationTests/Data/GetActionsResponseWithIntegrationData.json
- Added Integration Information to Get Actions response.
- Fixes issue #710 
- [SDK-4982](https://auth0team.atlassian.net/browse/SDK-4982)
[SDK-4982]: https://auth0team.atlassian.net/browse/SDK-4982?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Adds Integration information in Actions response

.github/workflows/build.yml, .github/workflows/release.yml, .github/workflows/rl-secure.yml, .github/workflows/snyk.yml, tests/Auth0.AuthenticationApi.IntegrationTests/Auth0.AuthenticationApi.IntegrationTests.csproj, tests/Auth0.Core.UnitTests/Auth0.Core.UnitTests.csproj, tests/Auth0.ManagementApi.IntegrationTests/Auth0.ManagementApi.IntegrationTests.csproj
- Update the actions/workflows to use .NET 8
JIRA -> [SDK-5289](https://auth0team.atlassian.net/browse/SDK-5289)
[SDK-5289]: https://auth0team.atlassian.net/browse/SDK-5289?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Upgrade build to use .NET 8

.github/workflows/release.yml
- Updated the versions of the following github actions 
- https://github.com/actions/deploy-pages/
- https://github.com/actions/upload-pages-artifact/
=> Use latest versions of actions for docs

CHANGELOG.md
- Update the ChangeLog to include heads-up of a potential compilation error in select cases.
- Refer https://github.com/auth0/auth0.net/issues/781
=> Update ChangeLog with for v7.30.0

src/Auth0.AuthenticationApi/Auth0.AuthenticationApi.csproj, src/Auth0.Core/Auth0.Core.csproj, src/Auth0.ManagementApi/Auth0.ManagementApi.csproj, src/Directory.Build.props, tests/Auth0.AuthenticationApi.IntegrationTests/PasswordlessTests.cs
- Refactoring `PasswordlessTest` class.
- Enabled few tests that were skipped.
- Added Directory.Build.props file for Centralised version management 
- [SDK-5859](https://auth0team.atlassian.net/browse/SDK-5859)
[SDK-5859]: https://auth0team.atlassian.net/browse/SDK-5859?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Refactoring PasswordlessTest and Adding Directory.Build.props

.github/actions/nuget-publish/action.yml, .github/workflows/build.yml, .github/workflows/release.yml, .github/workflows/rl-secure.yml, .github/workflows/semgrep.yml, .github/workflows/snyk.yml, src/Auth0.Core/Auth0.Core.csproj
- Bumps [actions/checkout](https://github.com/actions/checkout) from 3 to 4.
- Updated Newtonsoft.Json from 13.0.1 to 13.0.3
- Bumps [codecov/codecov-action](https://github.com/codecov/codecov-action) from 5.3.1 to 5.4.3.
- Bumps [actions/setup-dotnet](https://github.com/actions/setup-dotnet) from 3 to 4.
- Bumps [actions/cache](https://github.com/actions/cache) from 3 to 4.
Closes the below dependabot PRs
- #832 
- #833 
- #834 
- #836 
- #840 
N/A
=> deps: Upgrade dependencies
